#+title: 镜花水月
#+date: <2023-08-22 14:48>
#+description: 我不需要一种语言来解释我，因为我是定义中的人类，人类定义人类自己，因此我定义我自己。热爱自己的热爱，和大自然交流共生，做人就应该做的事（不管是人类自己定义的自己，还是其他文明定义的人类），这应该就是我对世界定义的语言。
#+filetags: Essay Philosophy

今天冥想完，一睁开眼，正好看到窗户外打进来一束光，灰尘在光束里无规律的漫游。

眯着眼，好像看到了七彩的颜色。

这让我突然想到了波长这个问题。也是因为昨天和朋友讨论到了[[https://music.163.com/?from=infinity#/song?id=568915923][7.23前夜 - 虚极乐队 - 单曲]]这首歌，

看评论说：

#+begin_quote
水樹：書中記載我們人類和宇宙之間溝通最 和諧的波長是7.23公分，密宗藏傳佛教的咒 文“嗡啊吽”這三個聲音的波長也是7.23公分，我覺得宇宙大爆炸的時候所有分子，量子泡沫，光子等等所有的物質它們之間感應 出來最和諧最完美的波長應該也是7.23公分，如果是這樣的話那麼我們的老宇宙該多美.
#+end_quote

眼睛盯着这束光发呆，突然脑海中一大堆信息也好像开始沿着这束光，在飞速的盘旋加速，冲破大气层，冲向无边黑暗的宇宙。

突然一瞬间，这束夹杂着思绪信息的光束，碰到了一个实体，迸发出了一个新的思考，也就是今天想整理出来的东西。

* 一

对于世界是什么，这个问题，或者说[[https://zhuanlan.zhihu.com/p/377161628][形而上学]]问题，

#+begin_quote
引自《国外哲学大辞典》：

【形而上学】（英 metaphysics）该词原为古希腊亚里士多德一部著作的名称，意为“物理学之后”。从13世纪起，被作为哲学名词，用于指研究超经验的东西的学问，或用作哲学的别称，其意一般多指建立一个观念体系以对实在的性质作出判断，或以一种方法去把握所知的实在的性质。

在德国黑格尔提出唯心辩证法以后，它又被用以指非辩证法的世界观与方法论。形而上学的核心问题是现象与本质的对立，围绕这个核心问题，哲学家提出了各种不同的观点。

形而上学，是西方哲学对世界或事物存在的基本哲学观点，也是西方哲学的基本理论形式。那么，究竟什么是形而上学？

简单而论，所谓形而上学就是指人们基于对人与世界存在的抽象性、一般性和普适性认识论体系。形而上学理论的基本特性，是以语言、概念等形式表现出来的抽象性；而关于事物存在的研究，是一种广义地、普遍的一般性研究；其理论的适用性，表现为对一切事物存在的普适性。

也可以这么说，形而上学理论体系，是在抽象的基础上关于一切事物存在的、真理性的“大一统理论”，即“放之四海而皆真”，与中国传统哲学的“道”具有相似性。

“形而上学”一词翻译自英文metaphysics，古[[https://baike.baidu.com/item/希腊文/5623773?fromModule=lemma_inlink][希腊文]]τὰ μετὰ τὰ φυσικά，拉丁文metaphysica。

该词原为[[https://baike.baidu.com/item/亚里士多德/26769?fromModule=lemma_inlink][亚里士多德]]一部著作的名称，该著作是亚里士多德死后200多年由[[https://baike.baidu.com/item/安德罗尼柯/22607214?fromModule=lemma_inlink][安德罗尼柯]]把他专讲事物本质、灵魂、意志自由等研究经验以外对象的著作编集成册，排在研究事物具体形态变化的《物理学》（physica）一书之后，并名之为《 *物理学之后诸卷* 》。[[https://baike.baidu.com/item/古希腊/14206?fromModule=lemma_inlink][古希腊]]文是去掉[[https://baike.baidu.com/item/冠词/1522215?fromModule=lemma_inlink][冠词]]就成了[[https://baike.baidu.com/item/拉丁文/360796?fromModule=lemma_inlink][拉丁文]]，meta这个前缀有之后、超越、基础的意思。这个用语被[[https://baike.baidu.com/item/拉丁语/747781?fromModule=lemma_inlink][拉丁语]]注解家 *理解为“超物理科学”* ，亚里士多德在书中讨论的问题成为了形而上学的很多基本问题。

“形而上学”一词在亚里士多德时代并未出现，它是在公元前60年[[https://baike.baidu.com/item/安德罗尼柯/22607214?fromModule=lemma_inlink][安德罗尼柯]]编撰亚氏遗著时，把所谓《形而上学》的各篇章放在《物理学》之后，并集合在一部书内，取名为Meta physika，即《形而上学》。 [7]

“metaphysics”的[[https://baike.baidu.com/item/中文译名/7123648?fromModule=lemma_inlink][中文译名]]“ *形而上学* ”是根据《 *易经* ·系辞》中“ *形而上者谓之道* ，形而下者谓之器”一语，由日本[[https://baike.baidu.com/item/明治时期/12594349?fromModule=lemma_inlink][明治时期]]著名哲学家[[https://baike.baidu.com/item/井上哲次郎/6660363?fromModule=lemma_inlink][井上哲次郎]]翻译的。 [[https://baike.baidu.com/item/严复/119000?fromModule=lemma_inlink][8] 晚清学者 *[严复]]* 则采用了玄学这一翻译，后经清末留日学生将大批[[https://baike.baidu.com/item/日制汉语/2018709?fromModule=lemma_inlink][日制汉语]]（日本称和制汉语）带回国后，玄学这一译法渐渐被形而上学取代。[[https://baike.baidu.com/item/严复/119000?fromModule=lemma_inlink][严复]]拒绝使用[[https://baike.baidu.com/item/井上哲次郎/6660363?fromModule=lemma_inlink][井上哲次郎]]的翻译，根据老子《道德经》"玄之又玄，[[https://baike.baidu.com/item/众妙之门/159328?fromModule=lemma_inlink][众妙之门]]"，把“[[https://baike.baidu.com/item/metaphysical/53056054?fromModule=lemma_inlink][metaphysical]]”一词译为玄学，但由于日本翻译的一些词汇更被当时的中国民众所接受，因此“形而上学”一词扎根在了汉语之中。
#+end_quote

今天这道光束之旅让我有了新的感受。

语言，肢体动作，眼神，视觉，听觉，触觉，人类从听摸看，开始了解这个物质世界。人类为了生存本能的反应和思想，表达或表现出语言和肢体动作，这应该是人类对于世界的第一次反馈和交流。

从本源出发，波长（光，声音），表达在数学是公式，表达在物理是图像和模型，表达在音乐上是音阶，一个微观物质分子和由它组成的宏观实体，经过人类的解码和编码，再转码成无限的表现或表达形式，也可以说，这就是人类的认知过程。

人类的社会形式不断发展，对世界的认知从神学到哲学再到现在的科学，但这些从基因里遗传下来的人的本性或者人之所以被定义为人的原始的东西，没有改变，

简单来说，和编程没什么区别，就是：理解和表达，我们无时无刻的在解码和转码这个世界。

马克思说，劳动分工，分化出职业和阶级，不同的社会形态，人类文明，对应着人类不同的生活和生存方式。

因此抛开现在人的社会属性，世界对于我们来说是什么，其实从头到尾都只取决于我们自己，只取决于我们和大自然的交流。

* 二

因此不如类比计算机编程语言来思考下去。

相同的信息和信号，通过不同的计算机语言，C,Go,Python，Java，通过同一硬件介质计算机，展现成功能相似的不同程序。这和人类解释世界其实没什么区别。

以历史唯物主义举例(也就是一种语言)，历史唯物主义指出：历史发展是有其特定规律的，即生产力决定生产关系，生产关系对生产力有反作用，生产关系一定要适应生产力的发展。伴随着生产力的发展，人类社会从原始社会，奴隶社会，封建社会，资本主义社会，社会主义社会，最终走向共产主义社会。

人类有太多解释这个世界的语言了，只是取决于你更相信哪一个，更喜欢哪一个。

而科学，作为人类历史和经验总结的全部（可以类比为操作系统或者根语言），我总觉得，它的局限性一部分来自于，我们没有除了人类之外的高等文明参照系。

形而上学的难处，就在于，我如何用我的意识去否定或肯定我的意识，就好像让一个计算机语言去编译和解释他自己。

*我们始终在用自己发展出来的价值观和世界观来反思我们自己，*

*我们如何用既定的思维和认知来冲破既定的思维和认知，*

这是个很矛盾的问题。

Add：在这里有我更多的思考：[[https://wiki.vandee.art/#On%20the%20Nature%20of%20Time%20-%20%E6%97%B6%E9%97%B4%E7%9A%84%E6%9C%AC%E8%B4%A8][On the Nature of Time - 时间的本质]] ，很开心，在时隔一年之后，自己的猜想得到了验证。2024-11-05

* 三

想到这里，其实已经豁然开朗了。又让我想到了黑客帝国。

按照现在的世界观，既然基因决定了人类的生物特性，现在科学的世界观是我们人类自己解释自己的语言，

那么，我们为什么要按照这些规则去生存或表达自己呢？或者为什么不按照物质本源的规律去生活和表达自己呢？（如果这个世界存在人类定义的本源的规律的话）

为什么只是选择一种主流流行的语言去解码和编码我的世界和生活呢？

而不是回到人类规则的原点：也就是开头所说，和大自然的交流，和大自然本身的理解和表达。

*我不需要一种语言来解释我，*

*因为我是定义中的人类，*

*人类定义人类自己，*

*因此我定义我自己。*

热爱自己的热爱，和大自然交流共生，做人就应该做的事（不管是人类自己定义的自己，还是其他文明定义的人类），这应该就是我对世界定义的语言。

如果硬要我选一个最喜欢的语言，

那一定是艺术了。
