#+title: 读或听或看？
#+date: <2023-09-18 17:58>
#+description: to understand something, you must actively engage with it.
#+filetags: Thinking


再给自己开个小坑，也是记录一下从RSS订阅到现在的信息输入方案给自己的反馈。

去年从RSS订阅开始，是一个实验，想看看文字信息阅读和视频、音频信息之间对于我来说，哪个效率更高，最终是想得出一个文字信息和视频信息之间的权重，每年再根据想了解的领域微调，作为一个信息输入模板固定下来。

近一年，基本没有过多的主动视频信息的摄入，感觉也还挺不错，有种吃完大荤，涮点青菜的感觉，很清爽。

* 再聊“读书无用”

Andy 的 [[https://andymatuschak.org/books/][Why books donʼt work   Andy Matuschak]] (就是 [[https://notes.andymatuschak.org/zNUaiGAXp21eorsER1Jm9yU][Evergreen notes should be atomic]] 那个 Andy)，大致讲了这么个事：

#+begin_quote
*为什么 “读书无用”*

[[https://andymatuschak.org/books/][Why books donʼt work]] 其实主要探讨了为什么书籍和演讲作为传统的知识传递媒介的局限性。

作者首先没有否认书籍的重要性，但我们扪心自问读过的很多书，真的能吸收的又有多少呢？可能读完的时候认为自己能把书的内容大致总结一遍，过段时间可能只能记得一些零碎的句子，再过一段时间可能不看目录根本想不起这本书主要讲什么。

紧接着作者开始从 “为什么讲座无用” 来侧面解释 “读书无用”。作者认为这两种媒介都有问题，因为都犯了 *transmissionism* （直译过来，传输主义？）的错误，

- 讲座，指望着听众从头到尾听到每句话，然后就能完全理解演讲者的观点了
- 读书，指望着读着通过阅读句子来理解知识，作者用文字描述一个知识，读着从头到尾读过，就理解了。

这些都是不科学的，因为它们没有调动起我们人类真正掌握知识的方式 —— 即我们认知的过程。

*to understand something, you must actively engage with it*.
#+end_quote

信息输入的载体，还是得量体裁衣，关键在于认知的过程。也就是 Andy 所说的，to understand something, you must actively engage with it.（2024-10-28-add：Andy 算是我 PKM 和笔记的启蒙导师了，现在的 tiddlywink 就是仿造 Andy 个人网站的翻页效果。）

*对于自主学习而言：* 扁平化的信息，简单来说即文字信息，更有利于调动自主的学习。

*对于知识吸收效率而言*: 立体化的信息，无疑在短期理解和吸收方面，效率更高。视频、音频的载体包含更多更直接的信息，更有利于信息的直接吸收。


* 扁平化信息or立体化信息

先简单把文字信息定义为扁平化信息，视频、音频等信息定义为立体化信息。

设定大前提：信息传播是一定有损耗的。

对于信息传播者来说，立体化的信息载体无疑可以包含更多信息的元素，对于信息接受者来说，当然理论上就可以接收到更多的信息。问题是出现在信息接收之后，也就是调动认知的这个过程。

*信息损耗率+认知调动率 = 新认知迭代率*

- 对于认知调动，比较明确：就是要做自主的信息再输出, to understand something, you must actively engage with it.

- 而对于信息损耗率，这个就因人而异了，如果听书和看视频对于你来说效率更高，一下就能记住很多信息，那么它对于你来说就是一个优秀的形式。

而对于我来说，现阶段，我更喜欢文字信息，也就是扁平化的信息。（2024-10-28-add：现在我已经体会到文字信息带来的好处了，[[https://clip.vandee.art/2024/10/writes-and-write-nots---%E5%86%99%E4%BD%9C%E8%83%BD%E5%8A%9B%E7%9A%84%E5%88%86%E5%8C%96/index.html][2024-10-28-Writes and Write-Nots - 写作能力的分化 - Vandee's Clip]] ， [[https://wiki.vandee.art/#%E6%96%87%E5%AD%97%E9%98%85%E8%AF%BB%E7%9A%84%E7%89%B9%E6%9D%83][文字阅读的特权]]）

原因有几点：

- 文字所包含的直接信息更少，但间接信息更多
  - 直接信息是指，文字的表面意思。比如最近在看的资本论，原文是真的拗口，能直接理解到的信息不多。
  - 间接信息是指，文字所想表达的信息。还是说资本论，马克思的一个小概念后面，可能都可以写一篇论文了，想要理解吸收这些概念，自然就会自主的去查。
  - 文字信息所呈现给你的很单一很具体，因此注意力的损耗相对会低一些。没有视频、音频信息的介入，我所面对的就是纯粹的思想提炼，和自己的思维碰撞。
- 视频所包含的直接信息更多，但间接信息更少
  - 看视频的时候，注意力不会完全集中在实质内容上，视频会让你分散一些注意力在它这个形式本身，可能是这个up长得很帅很好看，或者是视频效果很炫酷等等。这些声音和图像不会完全是和你想输入的内容完全相关，这是一部分注意力的损耗，视频的间接信息被这些占用了，而图书文字就是一张白纸。
  - 视频更像是一个窗口，我觉得这和把书和文字捧在手上的感觉还是很不一样的
    - 比如，打开一个北京大学的视频课，它更像是一个信息的窗口在你的对面，始终感觉隔着点什么。我调动的是视觉听觉和很多联动的反应来应对这个信息的窗口。时间久了，它好像更像是一个在发生的事件。
    - 而看书的时候，我更自由一点,可能感觉跟实在点吧，这本书是我的。和视频对比，更让我感觉这是一个纯粹学习的过程。它不是一个事件，而是我本来就在思考的海洋，现在汇入了另一个思考的溪流。
    - 我个人更喜欢这种感觉，你也可以说看书和视频对于你而言，看书更像是一个事件。


听书这个形式另说，比较特殊。本质上是信息的呈现，从视觉变成了听觉。

很多人没有整块独立下来的时间来安静的阅读，碎片化的时间听个书，是个很好的“看书”的方式。在心力不是足的情况下，就不应该选择要消耗很多心力的形式，这个时候，放松的信息输入形式，更好。不足的地方可能在于，内容的结构和体系不如文字直接，文字有直接的提纲和标题。但，在认知调动的时候可以自主总结，或者逻辑思维足够的情况，听下来也就把大纲固定下来了。

* 最后

#+begin_quote
For me, taking notes helps make sure that I’m really thinking hard about what’s in there. If I disagree with the book, sometimes it takes a long time to read the books because I’m writing so much in the margin.

*对我来说，做笔记有助于确保我真正认真思考其中的内容。如果我不同意这本书，有时需要花很长时间才能读完这本书，因为我在页边空白处写了太多内容*

— [[https://youtu.be/eTFy8RnUkoU?t=11][Bill Gates]]
#+end_quote

#+begin_quote
Text is a form of communication. If something, or someone wrote it for us, certain decisions were made along the way to convey the goal that we gave. Out of the many paths possible to crystallize that piece of knowledge into a piece text, one of them was chosen.

文本是一种交流形式。如果有什么东西，或者有人为我们写了它，那么我们就会在整个过程中做出某些决定来传达我们给出的目标。将知识结晶成一篇文本的多种可能途径中，我们选择了其中一条。

Source: [[https://lopespm.com/notes/2023/07/02/writing-as-a-form-of-thinking.html][Writing as a form of thinking - Byte Tank (lopespm.com)]]
#+end_quote
