#+title: 富有的概率
#+date: <2023-11-20 14:54>
#+description: 对于生命本身而言，它确实可以说是有目的性的，细胞分裂是你无法阻止的生命的脉动，贪婪的基因其实只有一个目的，让自己无限复制下去。但对于宇宙和物质而言，或许就是回到大爆炸的原点，无限膨胀再坍塌、无限收束、压缩。还有在诺兰电影信条里被大家熟知的热力学第二定律，熵增加原理。每时每刻发生的事情，都是概率。用这种极其不确定的概念来体会现实中看似确定发生的事情，挺美妙的。
#+filetags: Thinking Essay Ramble


* 薛定谔的富有

做梦中彩票这种事，我天天也在想，正好这两天看到了这些，挺有共鸣。[[https://letters.geekplux.com/51/?ref=geekplux-lab-newsletter][为什么要慢慢变富]]、[[https://www.bilibili.com/video/BV14c411u7S4/][【绝对珍藏】桥水创始人瑞·达利欧讲解 '不断变化的世界秩序'动画完整版 40分钟【中英精校】_哔哩哔哩_bilibili]]

从经济学角度来思考问题，确实可以让现实的问题简单一些，它不像哲学那样弯弯曲曲，直接的经济学模型带来直接的计算结果。

[[https://letters.geekplux.com/51/?ref=geekplux-lab-newsletter][为什么要慢慢变富]]里作者说到：

#+begin_quote
fortune 有幸运也有财富的意思，实际上这两个词也基本划等号。

...

众所周知我们的人生就是一场概率的游戏，这个说法我都说过无数次了。天降横财、一夜荣华、时来运转的概率和买彩票差不多。相对于这些不确定的事情，我们能掌握的可能是那些收益率低于 5% 的事情。这些事情可大可小，可以跟金融相关也可以跟自身提升相关，总之有正向收益的事情，你都可以把它理解成**增加确定性**的事情，也即增加概率的事情。比如：...

...

如果把变富看作一场赌博，那么我们应该赌概率大的事情，而不是收益率大的事情，赌长期的事情，而不是短期的事情。其实对于每个普通人，只要不去做一些突破自己认知但又完全无法衡量风险的事情，基本上是不会回退的。那么，你变富就是一件确定的事情。也许选择比努力重要，但努力决定了确定性的大小。

所以，慢慢变富其实是一种复利，既然是复利，那它的增长就是指数型的。只要我们每天还在进步，那我们缺的就不是那些让人焦虑的快速致富的机会，而是时间。一口吃不成胖子，但一口一口吃，总有一天会胖的。我们也许要做的是尽量延长自己玩这个长期游戏的时间。

...

很大程度上，变富实际上是认知在增长，也许等我们认知水平到了一定程度，财富自然而然就来了。而且，这个过程会是非常有趣的，会是一种享受，持续的增长会释放内啡肽，过快的刺激只会带来多巴胺。
#+end_quote

fortune 有幸运也有财富的意思，实际上这两个词也基本划等号。许多复杂的谜题的答案，往往就是题面本身。

随着了解初步的量子力学、决定论、宇宙目的论等概念，我逐渐对一些观点有了倾向性：

- 对于生命本身而言，它确实可以说是有目的性的，细胞分裂是你无法阻止的生命的脉动，贪婪的基因其实只有一个目的，让自己无限复制下去。但对于宇宙和物质而言，或许就是回到大爆炸的原点，无限膨胀再坍塌、无限收束、压缩。还有在诺兰电影[[https://movie.douban.com/subject/30444960/][信条]]里被大家熟知的热力学第二定律，熵增加原理。
- 每时每刻发生的事情，都是概率。用这种极其不确定的概念来体会现实中看似确定发生的事情，挺美妙的。最近还下单了个龟壳，学学周文王。**在不确定性中寻求希望中的确定性**，也就是人类一直在做的事情。

所以其实每个人都有富有的可能性，只是你还没有到达“富有态”🤣，可能性的大小不一样罢了。我们应该做的也是其实能做到的，就是增加这种可能性的大小。

* 提升自己是最大的储蓄

*很大程度上，变富实际上是认知在增长* ，也许等我们认知水平到了一定程度，财富自然而然就来了。

我一直很赞同这个观点。之前看到一句话：你只能赚到你认知范围以内的钱，也是一个意思。fortune，真正的富有一定是两方面的：财富富有和精神富有，也真就和字面一样，是种幸运。应该没有人会讨厌活着拒绝真正的'‘富有“，但正如罗翔在[[https://www.bilibili.com/video/BV1j84y1D7pP][【麦家x罗翔x衣戈猜想】人生海海，错了再来]] 里所说，正如一个智者所说：名利，它可能追逐的，就是那些并不在乎它的人。

富有从来不是真正富有的人本来的目的，它是伴随的一个概率。该有的都有了的时候，你想不富有其实也挺难的，名利会追逐你，甩都甩不掉，甚至反过来吞噬你。当所有的导向富有的概率事件都发生了的时候，最后那一点别人没有的”运气“，才是fortune真正到来的时候。当然这个运气，也可以说成是你的实力、命运，或者缺少这个运气的人的抱怨和忌妒。

*提升自己就是最大的人生储蓄，最大的财富。* 当然富有了之后，它是真理，富有之前，它是一坨shit。

瑞达利欧的《原则》，看了一点开头就一直放着了，现在确实还看不懂。[[https://www.bilibili.com/video/BV14c411u7S4/][【绝对珍藏】桥水创始人瑞·达利欧讲解 '不断变化的世界秩序'动画完整版 40分钟【中英精校】_哔哩哔哩_bilibili]]里提到的经济周期，宏观的经济运行规律，是从历史的不确定性中找到确定性，瑞达利欧总结出这些，称作原则。

但历史的进程和拐点，往往来自于那些不确定性，往往是这些不确定的人做出的不确定的事带来新的稳定与秩序。乔布斯不去”剽窃“施乐的图形界面，就不会有现在的苹果、比尔·盖茨不去接着”剽窃“苹果也不会有现在的微软、余华也想不到自己找了一个文化馆的工作到后来写出了《活着》、爱因斯坦质疑牛顿经典力学提出相对论、马云去了一趟美国回来忽悠了一帮朋友创建了阿里。

你以为我接下来会说，所以我们要向上面说的那些人那样啥的啥的，并不是，这些历史的结果和他们并没有什么绝对的联系。

我今天一出门，无非两个结果，出太阳了，还是出太阳了。


* Reference

- [[https://letters.geekplux.com/51/?ref=geekplux-lab-newsletter][为什么要慢慢变富]]
- [[https://www.bilibili.com/video/BV14c411u7S4/][【绝对珍藏】桥水创始人瑞·达利欧讲解 '不断变化的世界秩序'动画完整版 40分钟【中英精校】_哔哩哔哩_bilibili]]
- [[https://www.thepaper.cn/newsDetail_forward_24958915][作家余华已死，网红余华活着]]
