#+title: 艺术的模仿游戏
#+date: <2024-07-30 21:15>
#+description: 这些重构就根据不同的大脑结构分成了许多种：文学家写文学、科学家做研究、艺术家做艺术品。所以我不喜欢深究概念，无常才是常，无序才是秩序。我们仅仅是在做自己生物结构擅长、喜欢做的事而已。基于每个差异化的个体，对于自然、物质世界实时的反馈。所以艺术就是模仿么？我更愿意说，艺术是所有物质世界信息与反馈的一个巨大巧合。
#+filetags: Ramble Essay Art


* 模仿、游戏、亵渎

[[https://mp.weixin.qq.com/s/1Lz276s_RjdaSN3NXOIuHw][模仿、游戏和亵渎]]，RSS推送了这个订阅。如果你也喜欢思考，那么大概率你也会爱上这篇文章里提出的思考。

你可能会厌烦我在这类post里列举的大篇幅原文和我的原文，它们占据了页面里的许多篇幅，占用了你的注意力，让你现在就想赶紧滑过去看到下一个醒目的标题。你可能也会同样厌烦我在这些原文里留下的思维痕迹，没有提供给你一个纯净的思考空间。

对我而言，在写这些类似读书笔记的post时，它就像是一场无关时间和空间的另一个时间线可能存在的对话。这类post大多也没有具体行文的逻辑，因为这就是思考在最初的样子。我想尽力还原这个纯净的思考空间。

#+begin_quote
除去用于维生所需，人每天还有大量能量剩余，有些人多到会溢出，必须加以消磨。有人因此思考自身处境，就有了宗教和艺术。有人因此考虑世界和存在，就有了哲学和科学。有人因此觉察到匆匆的时间之流，意识到自己只是一个个连续的此时此刻在不断流逝，因而想要抓住永恒，于是有了形形色色的创造物。一切都是易逝的，唯有回忆留存，创造物可以记录瞬间，可以唤起回忆，因此它是永恒的表征。溢出的能量让人去创造。而创造就是模仿。
#+end_quote

在[[https://www.vandee.art/2023-11-24-something-about-boring.html][都是因为无聊]]里我从另一个角度也思考到了这个问题：

#+begin_quote
无聊同样也是想象力的来源，人类进步的来源。

阿基米德洗澡的时候无聊，发现了浮力；牛顿在苹果树下面无聊（有争议），发现了万有引力；伽利略对着天空无聊，发明了天文望远镜进一步证实了哥白尼的日心说；达尔文喜欢对着动植物无聊，提出了自然选择；爱因斯坦对着时间无聊，想搞清楚时间到底是什么，提出了相对论；尼古拉・特斯拉对着黑夜无聊，做出了第一个交流电发动机（本人讨厌爱迪生）；

人对着木头无聊，点着了火。
#+end_quote

最近巴黎奥运开幕式国内外的争议很多。草草的浏览了国内外主流平台的新闻言论和一些关注的RSS推送，还是这篇最炙热，这些文字让我的大脑像火锅里被烫的猪脑一样炙热滚烫：

#+begin_quote
就像是只要出现一张长条桌，再安排13个人坐在那里，亵渎的潜在可能性就已经产生了。因为13个人加一张长条桌，作为一种对于历史和宗教的模拟，已经被确定为特定的形式。有人借用这个形式重新模拟，构成一个游戏的一部分，那么就会和部分人的特定解读相互冲突。但是占据形式这个想法本身，不就是个很荒谬么？印度教徒或者佛教徒，不会宣布垄断打坐这个形式，不会因此有一只猫或者一个朋克摆出这个姿势就会让他们上火。从游戏的角度来看，感到亵渎或者愤怒本身就是游戏成功的象征。

因为一次模拟就是一种重构，就是一次重新解读，就是在回忆之海里投入一个新的锚标。模仿本身就具有一种邀约的姿态，邀请另外一个人来观看，从另外一个角度去观看他认为熟悉的事物。当这个人不愿意从他熟悉的事物上离开自己惯常的理解，碰撞就已经发生，游戏的使命其实已经完成。一个寂然无声，没有任何反馈的游戏才是失败的游戏。
#+end_quote

艺术就是对我来说最有趣的模仿游戏了。

* 艺术和模仿

《艺术的故事》和《现代艺术150年》这两本书从历史的角度，阐述了一个让我担忧的结论：艺术本身可能并不存在，存在的只是艺术品。

现代艺术更不用说，资本引导着艺术的潮流。与印象派起源的19世纪初期到现代艺术萌芽的20世纪初期相比，艺术的自由早就不复存在了。现在已经看不到在巴提诺格里斯大街11号（现为克里希大街9号）的咖啡馆里曾经热闹的景象。保罗·塞尚、埃德加·德加、莫奈等大佬们，数年来他们都聚在这里，讨论艺术和人生（在这个阶段他们常常被简称为“巴提诺格里斯小组”）。印象派之父马奈的工作室就在附近。印象派小分队的成员都拿各自的生涯作赌注，决定不理会学院的那套系统，最终宣起了印象派革命。

正是那个时候革命与机械化就催生了一个被称为资产阶级的新的社会阶层。路易斯·勒罗伊做梦也不会想到，他对莫奈的绘画《日出·印象》的苛刻评论竟然催生出了伟大的印象派。资本的这些规则是与艺术同在的另一个推动力，没有资本的规则艺术品的价值可能永远不会被推到现代艺术的高度。它们固然很可恶但也激发着真正的“艺术家”去完成超越资本规则的艺术品。

也更难看到马塞尔·杜尚幽默叛逆的《泉》、保罗·塞尚《圣维克多山》独特的双视角理念对视觉透视的颠覆、达达主义对于现实的嘲讽、梵高向日葵的橙黄的炙热与癫狂的深蓝、毕加索《亚维农的少女》粗狂的立体主义几何色块、萨尔瓦多·达利《记忆的永恒》重构的想象力。

我喜欢艺术的根本原因是 *我喜欢关于创造的一切* 。[[https://mp.weixin.qq.com/s/1Lz276s_RjdaSN3NXOIuHw][模仿、游戏和亵渎]]的作者谈到：

#+begin_quote
而创造就是模仿，以前我没想明白这个问题，认为存在两分法，90%的模仿和10%的独创。不是这样的，只有模仿。模仿自然界的实际存在，于是有了古代艺术，岩壁上的手绘野牛，或者古埃及墓穴壁画里的花园，乃至古希腊人创作出来的惟妙惟肖石雕，都是模仿。

人会睡去，人会遗忘，人会死亡，眼前的一切转眼成空，所以要模仿。通过模仿实际存在，模仿现实世界，一张画，一座雕塑，都可以对抗这种无尽的消逝。很多年前的某个下午早已过去，早已消逝，早已遗忘，但是通过人为创造物，人们又可以回到那个下午，一切如昨。这件事情很重要，人需要不断确定自己处于连续不断的生命之流里，需要确认自己是一种连续的存在，方法就是在回忆中流畅地沿着时间线回溯到任意一点。而每一点都是曾经的此时此刻，所有的此时此刻加在一起，就是自己存在的证据。
#+end_quote

我不想去承认创造就是模仿这个事实，就像我不想去承认艺术可能其实并不存在这个事实。语言的表达是非常有限的，所以我更喜欢艺术的表达和逻辑辩证的表达。“而创造就是模仿”这句话，结合全篇的文章你也无法说明作者真正想表达的意思是什么，因为这牵扯到作者一生的经历。

我更愿意换句话来表达：创造易是模仿，对大自然的模仿。我喜欢用“易”来指代“亦”，类似于文言文里的通假字。“就是”在逻辑上表示一个或非的判断，在大的论点里我不喜欢用逻辑上的判断来表达观点，这样的表达在缺失逻辑推理过程时，难免会让人质疑，也没有那么绝对的事情。

我其实不喜欢深究概念本身，就像我喜欢印象派和抽象派一样。没有绝对的真实，只有每个人不同的印象。这些抽象的印象更加真实，每一个客观事实的实例对于不同个体在不同时空的意义都不会是相同的。水对于原子世界是 H₂O，它也是“上善若水”，它也是农夫山泉，对于地球生命它是生命之源。所以水是什么？回答这个问题，或者这个问题本身不重要，这些概念只是我们思维的重构，只是我们对物质的反馈。这对于水来说是不公平的，你会喜欢别人随便给你起外号么？印象派对于自然就包容太多了，而抽象派、超现实主义则在概念上进一步解构和重构。

把话题缩小一些，艺术创造就是模仿么？所有的创造都可以看作是对大自然的模仿，特别是艺术方面的创造。黄金比例是人类从数学角度对自然拙劣的模仿、透视法是从几何角度对自然空间拙劣的模仿、色彩科学是从光谱角度对自然的拙劣模仿。这里的“模仿”更准确的逻辑语义表达可能是“重构”，重构我们人类对于物质的解释与反馈。用计算机语言来说就是，物质给予了一个输入，人类大脑本能的反馈输出，我们不可能避免这个过程，因为这是生命的脉动。

这些重构就根据不同的大脑结构分成了许多种：文学家写文学、科学家做研究、艺术家做艺术品。

所以我不喜欢深究概念，无常才是常，无序才是秩序。我们仅仅是在做自己生物结构擅长、喜欢做的事而已。基于每个差异化的个体，对于自然、物质世界实时的反馈。所以艺术就是模仿么？我更愿意说，艺术是所有物质世界信息与反馈的一个巨大巧合。

我相信量子力学在未来的研究里一定会颠覆现代科学的认知结构。

* 创造力与记忆力

[[https://shwin.co/blog/creativity-fundamentally-comes-from-memorization][创造力从根本上来自记忆 --- Creativity Fundamentally Comes From Memorization]]，正好看到这篇推送，和前几天的post主题挺契合，几个观点挺有意思：

- 自治可以激发创造力

  #+begin_quote
Creativity comes to those who have internalized the patterns of their art -- they can see the connection or novelty because it's all in their head.

创造力属于那些已经内化了艺术模式的人——他们可以看到其中的联系或新奇之处，因为这一切都在他们的脑海中。

Therefore autonomy enables creativity, and a system helps achieve autonomy quicker.

因此，自治可以激发创造力，而系统有助于更快地实现自治。
  #+end_quote

- 系统并不直接产生创造力，而只是激发创造力

  #+begin_quote
The key here is memorization's role in learning. We often tout the difference between memorization and true "understanding", which are indeed distinct. Memorizing the different methods of attacking mathematical integrations is different from being able to use the right one in the moment.

这里的关键是记忆在学习中的作用。我们经常吹捧记忆和真正的“理解”之间的区别，这确实是截然不同的。记住攻击数学积分的不同方法与能够立即使用正确的方法是不同的。

But I maintain that such pattern recognition is just another form of memorization, though often a more subconscious one. This is learned from repeated exposure, and what I'm attempting to do when I try to see a "breadth" of cases after learning the framework and available patterns to use.

但我坚持认为，这种模式识别只是记忆的另一种形式，尽管通常是一种更潜意识的形式。这是从反复接触中学到的，也是我在学习框架和可用模式后尝试查看“广泛”案例时尝试做的事情。

What this is really doing under the hood, is creating a heuristic and... wait for it... memorizing it!

这实际上在幕后做的事情是创建启发式并且......等待它......记住它！

Once this heuristic is internalized, it becomes a new primitive and we focus our attention to higher-level problems.

一旦这种启发式被内化，它就成为一个新的原语，我们将注意力集中在更高层次的问题上。

Once a dancer learns the fundamental movements of their specialization, they're able to improvise. So are pianists once they learn scales, and mathematicians (though sadly many of us never experience the joy of mathematical improvisation -- as Paul Lockhart covers in his [[https://worrydream.com/refs/Lockhart_2002_-_A_Mathematician's_Lament.pdf][Mathematician's Lament]]).

一旦舞者学会了其专业的基本动作，他们就能够即兴创作。一旦钢琴家学习了音阶，数学家也是如此（尽管遗憾的是，我们中的许多人从未体验过数学即兴创作的乐趣——正如保罗·洛克哈特在他的《数学家的挽歌》中所提到的那样）。

The key is understanding that a system doesn't directly *make* creativity, it just *enables* it. Memorization’s role is similar.

关键是要理解系统并不直接产生创造力，而只是激发创造力。记忆的作用是类似的。

Another strategy that works well in both humor and famous EDM drops is "violating the expectation", but you need to know the expectation before you can violate it. Once you learn music theory, you're able to violate it in ways that resonate. Avant-garde art requires knowing what the establishment is to push the boundaries as orthogonally as possible.

另一种在幽默和著名 EDM 中都有效的策略是“违反期望”，但在违反期望之前您需要先了解期望。一旦你学习了音乐理论，你就能够以引起共鸣的方式违反它。前卫艺术需要了解其体系是什么，以尽可能正交地突破界限。
  #+end_quote



* 模仿游戏

[[https://movie.douban.com/subject/10463953/][模仿游戏]]是我很喜欢的一部电影，讲的是图灵（本尼迪克特·康伯巴奇 Benedict Cumberbatch 饰）制作密码破译机的故事。电影的名字和今天讨论的模仿游戏完全是一个巧合。只是在重复敲打模仿、游戏时，这个电影一直在我的脑子里窜来窜去，干脆把你放出来好了。黑客帝国也放出来好了，[[https://www.vandee.art/2023-02-23-blue-or-red.html][蓝色药丸还是红色药丸？]] 🤣。

现在的LLM大语言模型同样是一个模仿游戏。LLM是一个巨大的ZIP文档，它是一个世界的快照，压缩了快照时间点互联网、人类知识的巨大信息，是现实世界最大的模仿游戏，往后更会是人类历史的一部分，它既是记录者也是开创者。

在这个游戏里，人类千万别输了。

#+begin_quote
Being multidimensional means recognizing and nurturing the various aspects that make you who you are. Just like a prism splitting white light into different colors, imagine yourself to be made of those different "colors". You have a unique permutation of talents, and experiences. By accepting and practising these aspects of yourself, you can grow beyond the limits set by society's standard expectations.

多维意味着认识和培养使你成为你的各个方面。就像三棱镜把白光分成不同的颜色一样，想象一下你自己就是由这些不同的 "颜色 "组成的。你拥有独特的天赋和经验。接受并实践自己的这些方面，你就能超越社会标准期望所设定的限制，获得成长。

The most interesting part is: you get to define your own dimensions.

最有趣的是：你可以定义自己的维度。

 [[https://maharshi.bearblog.dev/become-a-multidimensional-person/][Be multidimensional, anon | Maharshi's blog]]
#+end_quote

我更喜欢艺术的模仿游戏。
