#+title: 2024 - 需
#+date: <2024-12-12 13:34>
#+description: 根据香农的信息论，社会可以被描述为一个复杂的通信系统，其中信息是基本构建块。社会成员通过各种渠道（如言语、文字、表情等）交换和传递信息，以实现合作与协调，其中个人和社会机构扮演编码器、解码器及信道的角色。通过总结的过滤和优化，个体能够更高效地压缩信息，减少误解，提高交流质量。在《智人之上》里更是强调了信息+想象可以发挥多大的作用。这几年我的许多出发点也都来自对信息的处理，明年也会继续。
#+filetags: Ramble

我给我今年的关键词是：需，是周易的一个卦象。卦辞：有孚，光亨，贞吉，利涉大川。尽管今年又新学了一些东西，但总体来说储蓄还远远不够。

我其实不习惯写总结，一直觉得没有太大必要，该做的都做了，没有做的也总结不出什么。但近几年有了新的看法。

2024 年 12 月 2 日，牛津大学出版社宣布“脑腐”（brain rot）为 2024 年[[https://corp.oup.com/news/brain-rot-named-oxford-word-of-the-year-2024/][牛津年度词汇]]，各大知名机构都会在年底公布它们今年的数据总结，政府同样会有经济总结、工作总结报告，虽然这些对外的属性较多，它们需要权衡各方面的利弊，公布一个对外的说法，但多少会反应出一些当年的趋势。不同立场的分析主体会带有主观偏向，但数据是实打实的。怎么判断形势、趋势？我觉得从这些总结报告入手，是个很好的方法，可以顺着找到相关的数据自己分析。

* 2024
自己的总结当然向内的属性就要偏重一些了。也一样从数据出发来分析。

这两年看的书还是太少，今年也没有达到一个月一本的目标，总共阅读了 7 本书：

#+attr_html: :alt  :class img :width 50% :height 50%
https://testingcf.jsdelivr.net/gh/vandeefeng/gitbox@main/img/books.png

Blog 共 13 篇，里面我觉得还不错的有：[[https://www.vandee.art/2024-05-22-org-pkm-manual.html][PKM（个人知识管理）构建手册 - Emacs]] 、 [[https://www.vandee.art/2024-05-05-the-value-of-art.html][也说说艺术的价值]] 、[[https://www.vandee.art/2024-11-21-recording-is-resistance.html][记录本身就是一种反抗 - gitmemo]] 、[[https://www.vandee.art/2024-03-15-the-weight-of-three-cabbages.html][三颗大包菜]] 。

总体来说，今年对 Emacs 更加精进了，PKM 也更加完善，已 Emacs 为主记录原始的笔记作为 PKM 基本库，迭代到 [[https://x.vandee.art/wiki][Vandee — Wiki]] 精炼成原子笔记，[[https://x.vandee.art/memo][GitMemo]] 带上社交属性来记录 Memo 并作为朋友圈替代，[[https://x.vandee.art/clip][Clip]] 剪藏有记录价值的文章，[[https://x.vandee.art/blog][Blog]] 作为写作的输出。这几个部署的分板块都迭代自 Emacs 原始的数据。

得益于 cursor，构建了 [[https://github.com/VandeeFeng/gitmemos][GitMemo]] 。又继续学习了 JavaScript、Rust、C、Python 等几种计算机语言。乐理基础也囫囵吞枣的又系统的看了一下，听了许多古典音乐，其中最喜欢的有 Vivaldi 的 The Four Seasons 四季。

今年主要在内核的修炼，我感觉我和自然的交融更加融洽了。这应该得益于《周易》和古典乐。

* 总结是在做什么？
我们有时会在一个阶段快要结束的时候产生一种时间过的很快的感觉，这其实是因为重复性的事物在日常生活中占据的比例比较大，所以我们会觉得每天做了许多，但又好像什么都没做，在大脑里就没有留下什么，于是在回顾的时候就会感觉，怎么时间一下就过去了？

以往我也会有这种类似的感觉，但这两年明显减少了。因为在每个月我都会自动有根据 Journal 生成的 AI 小结，每天我都有可以度量的具体事物，每个阶段都计划了任务。

总结可以放慢这些时间，用文字和记录来度量这些过去的时光。

更重要的是，每年把自己向内的总结和外界的总结一对比，就可以知道自己和外界的缝隙在哪里，在下一年做出针对性的调整。

根据香农的信息论，社会可以被描述为一个复杂的通信系统，其中信息是基本构建块。社会成员通过各种渠道（如言语、文字、表情等）交换和传递信息，以实现合作与协调，其中个人和社会机构扮演编码器、解码器及信道的角色。

通过总结的过滤和优化，个体能够更高效地压缩信息，减少误解，提高交流质量。在《智人之上》里更是强调了信息+想象可以发挥多大的作用。这几年我的许多出发点也都来自对信息的处理，明年也会继续。

以后每年就用周易的卦象名来总结，挺有意思的。
