#+title: 实用小玩意收集
#+date: <2024-07-26 13:42>
#+description: 汇总一些实用的工具、软件、网站，长期更新
#+filetags: Tool Useful

汇总一些实用的工具、软件、网站，长期更新。

阮一峰的GitHub weekly issues： https://github.com/ruanyf/weekly/issues ，可以找到许多有意思的东西。

日常的搜集第一次整理之后有了工具汇总表格版：[[https://app.teable.io/share/shrlzO2q7vyCEJYvXqa/view][tools]] ，这里做第二次筛选。

** My Favorites
- *Vimium*

  浏览器插件，可以用 Vim 模式来操作浏览器。最喜欢它的快速打开地址栏功能，兼并自定义搜索。在 Firefox 里，自定义了垂直标签栏，再加上这个，还要什么 Arc？
- *RIME*

  输入法就是笔。

  [[https://rime.im/][RIME | 中州韻輸入法引擎]]，配合 [[https://github.com/iDvel/rime-ice][iDvel/rime-ice: Rime 配置：雾凇拼音 | 长期维护的简体词库]]，多平台多端同步。已经使用了几年，非常巴适，手机端也可以同步配置。

  以前输入法就各种偷偷记录用户输入习惯，现在各个输入法又还要内置AI再记录一遍。本地配置、不需要联网的输入法是我的刚需，更何况，rime还可以自挂词库。

- *Napkin*

  一个可以根据文字内容生成关系图的在线笔记编辑工具，目前还在beta测试阶段可以免费体验PRO的内容，生产力提高不是一点点。生成的关系图可以再详细编辑标题，图标等等，支持导出为PNG、SVG、PDF。

  Url：https://www.napkin.ai/
- *Witsy*

  这就是目前我用过最好的 LLM PC 客户端。

  Url: https://github.com/nbonamy/witsy
- *PixPin*

  Mac的终于出来了。这是我用过最好用的截图软件了。

  PixPin的名字来源于“Pixel Pin”，简单来说是一个截图、贴图的工具，但是PixPin以截图和贴图两大功能为核心做了大量的优化功能，目标是提升用户在工作时的工作效率，无论用户使用电脑做何种工作，都可以使用PixPin提高工作效率。

  Url: https://pixpinapp.com/
** Mac
- FlashSpace: FlashSpace is a blazingly fast virtual workspace manager for macOS

  Github: https://github.com/wojciech-kulik/FlashSpace

  一个简单易用的管理工作区的项目，自定义快捷键就可以切换不同的工作区。平常把 Emacs 和浏览器单独放一个，终端单独放一个。
- Maccy：简单易用的剪切板管理工具

  GitHub：https://github.com/p0deje/Maccy
- Pearcleaner: A free, source-available and fair-code licensed mac app cleaner

  Github: https://github.com/alienator88/Pearcleaner

  轻量的软件卸载工具。
** Search
- *Gemini-Search*

  Perplexity style AI Search engine clone built with Gemini 2.0 Flash and Grounding

  https://github.com/ammaarreshi/Gemini-Search
- *OpenSearch GPT*

  A personalised AI search engine that learns about you and your interests as you browse the web.It's like a perplexity / searchGPT clone, but for *you*.

  开源AI 搜索引擎，使用了mem0来存储记忆。部署在Cloudflare上，作者仅用了一天制作完成。

  Url: https://opensearch-ai.pages.dev/

  GitHub: https://github.com/supermemoryai/opensearch-ai

  Twitter: https://x.com/DhravyaShah/status/1818469911490162784

  https://github.com/Dhravya/cloudflare-saas-stack  这是作者的之前的Cloudflare全栈方案。

- *Perplexica*

  GitHub: https://github.com/ItzCrazyKns/Perplexica

  perplexity的开源平替，GitHub 11.4K Star。可docker部署，支持ollama本地模型。由于它的网络搜索依赖于SearXNG，等于还附送了一个SearXNG的本地实例。

- *Grep*

  一个快速从GitHub仓库查找内容的网站，支持正则，可以直接搜索代码内容

  Url: https://grep.app/

- *devv.ai*

  程序员搜索利器

  https://devv.ai/zh

- *mwmbl*

  一个可以由用户提供爬取源的开源搜索引擎，github 文档里还介绍了其他许多优秀的搜索引擎
  https://mwmbl.org/

  GitHub: https://github.com/mwmbl/mwmbl

- *SearchGPT*

  OpenAI推出的搜索。

  https://openai.com/index/searchgpt-prototype/

** 论文

- alphaxiv：斯坦福大学的学生做的一个论文讨论平台。可以理解为基于arXiv论文的Twitter，可以对论文评论，讨论。

  If you find a paper on arXiv that you’d like to discuss, simply replace arxiv.org with alphaxiv.org in the URL.

  Url：https://www.alphaxiv.org/

- [[https://www.aminer.cn/][AI论文检索平台 aminer]]

- [[https://paperswithcode.com/][paper with code]]

  这是一个论文和对应工程实现（含代码、数据集、测试方法等）的索引工具。下次你看到别人推荐优质论文时，可以直接用它去找代码实现

- [[https://www.connectedpapers.com/][Connected Papers | Find and explore academic papers]]

- [[https://briefgpt.xyz/][BriefGPT - AI 论文速递]]  一个中文论文推送网站，还可以

- Intro: 一个非常好用的AI论文阅读工具：TXYZ

  Source:  https://www.txyz.ai/

** LLM Web Chat

- *DuckDuckGo AI Chat*

  DuckDuckGo推出的AI聊天网页。已更新GPT-4o。

  https://duckduckgo.com/?q=DuckDuckGo&ia=chat&atb=v409-1

- *HuggingChat*

  HuggingFace推出的AI聊天网页，支持最新的Llama 3.1-405B。

  https://huggingface.co/chat/

- *POE*

  一个聚合LLM聊天网站，可选择的模型很多，Flux也有。

  https://poe.com/

- *delve*

  一个可以根据回答内容递进搜索的AI聊天网页。

  https://delve.a9.io/

- *WinGPT*

  一个仿window风格的AI聊天网页，免费GPT-4o。

  https://wingpt.vercel.app/

- *ChatGPT-Next-Web*

  很早一批开始做GPT生意的了，他们这还可以买KEY。

  A cross-platform ChatGPT/Gemini UI (Web / PWA / Linux / Win / MacOS). 一键拥有你自己的跨平台 ChatGPT/Gemini 应用。

  在 1 分钟内使用 Vercel **免费一键部署**个人的GPT聊天实例。

  GitHub: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

- *Open WebUI*

  Open WebUI 是一个可扩展、功能丰富且用户友好的自托管 WebUI，旨在完全离线操作。它支持各种 LLM 运行程序，包括 Ollama 和 OpenAI 兼容的 API。

  docker轻松部署。

  GitHub: https://github.com/open-webui/open-webui

** Others

另见：表格版 [[https://app.teable.io/share/shrlzO2q7vyCEJYvXqa/view][tools]]

- Intro: 一个电子书翻译工具，7K star.利用大语言模型（如 ChatGPT、Claude 等）对文件和图书进行多语言翻译的制作，支持的格式有 epub、txt 以及 srt 等。最近，作者将之前吴恩达老师开源的翻译工作流整合到项目中，使得翻译的效果更加好。

  Source: https://github.com/yihong0618/bilingual_book_maker

- GitHub 上一个开源的终端 AI 助手 AI Shell。

  在终端命令行界面（CLI）上，可通过自然语言转换为对应执行的 Shell 命令，类似于 GitHub Copilot X CLI。

  GitHub：https://github.com/BuilderIO/ai-shell

- Stirling-PDF

  一个本地的处理 PDF 的工具，界面是 Web UI，可以支持 Docker 部署。

  各种主要的 PDF 操作都可以支持。比如拆分、合并、转换格式、重新排列、添加图片、旋转、压缩等等。这个本地托管的网络应用最初完全由 ChatGPT 制作，后来逐渐发展，增加了许多功能，以满足你对 PDF 的各种需求。

  Stirling PDF 不会对外发送任何数据以进行记录或跟踪。

  所有的文件和 PDF 要么只在客户端处理，要么只在服务器内存中暂存，用于执行任务，或者仅在执行任务时保存在临时文件中。一旦用户下载了文件，那些文件就会从服务器上删除。

  https://github.com/Stirling-Tools/Stirling-PDF

- 部署deeplx到cloudflare，比部署到docker方便

  https://github.com/ifyour/deeplx-for-cloudflare

- 功能颇为强大的 GPT 学术优化开源项目 GPT Academic，目前 60.2k Star！

  GitHub: https://github.com/binary-husky/gpt_academic

- Intro: 开源离线Notion,支持本地LLM，JavaScript自定义功能

  Source: https://github.com/mayneyao/eidos  、 https://eidos.space

*** PDF相关

PDF转Markdown 方案

1. document-convert（开源）：https://github.com/multimodal-art-projection/MAP-NEO/tree/main/Matrix/document-convert
2. Ragflow（开源）：https://github.com/infiniflow/ragflow
3. gptpdf（开源）：https://github.com/CosmosShadow/gptpdf
4. 百度云Textmind（闭源）：https://cloud.baidu.com/product/textmind.html
5. doc2x（闭源）：[[https://doc2x.noedgeai.com/][https://doc2x.noedgeai.com]]
6. 腾讯云文档解析（闭源）：https://cloud.tencent.com/document/product/1759/107504
7. marker（开源）：https://github.com/VikParuchuri/marker
8. PDF-Extract-Kit（开源）：https://github.com/opendatalab/PDF-Extract-Kit
9. zerox（开源）：https://github.com/getomni-ai/zerox
10. OminiParse（开源）：https://github.com/adithya-s-k/omniparse
11. MinerU（开源）：https://github.com/opendatalab/MinerU
