#+title: 羊好可怜
#+date: <2024-02-01 14:52>
#+description: 这让我突然想到超市猪肉包装上的卡通猪logo、电梯里最近的猪肉广告，是不是其实他们还是会心存愧疚，要不然为什么要把这个东西画的这么可爱，好像那个健康快乐的猪的形象可以让消费者联想到这个猪肉很健康，让我们从开始就觉得吃着这个健康快乐的卡通猪是一个也会让很快乐的事，就像电梯广告里卡通猪说的：我吃的健康，肉味更香（画面是一个微笑的大猪脸）。
#+filetags: Essay 局外人
#+options: toc:nil



* 羊好可怜

最近爱上了家附近的一家羊肉粉，很还原贵阳的风味。羊肉片的薄厚适中，量也不多不少，粉快见底了，肉也差不多吃完，辣椒面更是香而不呛喉。这种凝结于劳动实践中的精确剂量，比任何公式都要准确，随手一抓每次我吃来都刚刚好。虽然这样同样我也是被“算计者”，却全然没有被大数据计算的那种厌烦感。

吃了差不多有两个月了，本来每次都吃的香香的，全身暖和，直到今天。

从地铁出来，走过两个红绿灯，直行500米之后，我和往常一样又点了一碗。正夹起一片羊肉，突然听到身后一个小女孩说：妈妈，妈妈，羊好可怜啊。妈妈没说话，然后是小女孩的重复。

我没有回过头去看他们是不是还是点了一碗，也没有听清女孩妈妈最后说的什么，也许是她还是没想好怎么解释，也许是对店员的一个点头，可能是直接走远了所以听不到，可能是我注意力还是在香香的羊肉上选择性过滤了。我可以确定的是，她一定说了话，而我在一瞬间思考的空白之后，吃的还是挺香。

* 困扰

路上无数个关于善恶、佛教信仰、素食环保的问题相互纠结，后悔没仔细听听女孩妈妈是怎么回答的，这样我可能可以知道一个正确的答案或者排除一个错误的。不想清楚这个问题到不是很困扰我想以后小孩教育的事，最要紧的是这会直接影响我下一次吃粉的体验。我知道下一次我再吃的时候，一定又会再想这个问题。

困扰我的不是人应不应该吃羊的事；也不是是不是吃羊了就是大恶人，不吃就又日行了一善，少吃了一片就又积了一德。因为凭我现在的道行是一定回答不了的，所以干脆先丢到一边。

让我现在能困扰，又还能接着想想的是：我小时候究竟有没有问过这个问题（模糊的印象里我肯定说过）；为什么听到小女孩这个问题的时候，心里还是有犹豫。如果我是那个问题答案的任意一边，我都应该不会犹豫，我不知道我犹豫的是什么。我只想吃羊肉的时候还是香香的。

这让我突然想到超市猪肉包装上的卡通猪logo、电梯里最近的猪肉广告，是不是其实他们还是会心存愧疚，要不然为什么要把这个东西画的这么可爱，好像那个健康快乐的猪的形象可以让消费者联想到这个猪肉很健康，让我们从开始就觉得吃着这个健康快乐的卡通猪是一个也会让很快乐的事，就像电梯广告里卡通猪说的：我吃的健康，肉味更香（画面是一个微笑的大猪脸）。

小女孩的问题我可能会这样回答：我也这么认为，羊是真挺可怜的，你看替罪羔羊这个成语，羊也被用来祭祀和献祭。但《圣经》里也有说：“次日，约翰看见耶稣来到他那里，就说，看哪，神的羔羊，除去（或作背负）世人罪孽的。”（约翰福音1:29），同样也是基督教动物象征符号，象征耶稣及其追随者。

我知道，这次我又会是局外人了。因为，虽然下一次我还会再想这个问题，我也还是会吃的很香。
