#+title: 记录本身就是一种反抗 - gitmemo
#+date: <2024-11-21 19:04>
#+description: 我记录这些并不是为了反抗什么，虽然带着同样的目的，但手段可以就是手段，它不象征任何。扫地僧扫地其实并不是为了什么，它只是在扫地，它的手段和目的已经融为一体互相转化了，但又不通过任何目的来驱使这个手段。
#+filetags: Ramble

[[https://www.vandee.art/2024-10-28-memos-and-ssl-config.html][还是入坑了 Memos]] ,大概一个月之前在 VPS 上部署了 memos，挺好玩的。也是因为这几天服务器的 IP 突然被 GFW blocked 了，memos 的数据备份到不是很麻烦，长期来看，我大中华的网络太不稳定了。

很久之前就看到这个利用 GitHub issues 构建博客的项目：[[https://github.com/yihong0618/gitblog/issues/177][gitblog]] ,作者 yihong0618 和我的许多想法都很相似。

思来想去还是决定把 memos 迁移到 GitHub 上记录。

[[https://laike9m.com/blog/people-die-but-long-live-github,122/][People Die, but Long Live GitHub]] 这篇文章里写到：

#+begin_quote
GitHub 已经成为互联网最重要的基础设施之一，有太多人，太多事都直接或间接地依赖于 GitHub，除非人类在未来完全不需要开源代码(这显然不可能)，否则我想不出 GitHub 有关闭的可能。对 GitHub 来说，存在 100 年简直是小意思，500 年也不是不可能。这是我的预言，不一定准确，但我还挺有信心的。

人总想留下某种痕迹，证明自己活过，然而事实上，99.999%  的普通人就这么被历史遗忘了——曾经是这样。我们处在信息时代的早期，同样也处在人类文明的早期。从今往后，被数字化的东西只会越来越多。既然有人意识到了 GitHub 的独特性，随着时间推移，越来越多的人总会意识到。那时候会发生什么？自然是，越来越多的人会把自己的信息搬到 GitHub 上，依托 GitHub  实现曾经人们可望而不可及的"永生"。人有两次死亡，第一次是肉体，第二次是被人忘记。我忘记这句话是谁说的了，但现在我们已经可以回避第二次。只要  GitHub 支持，就一定会有人这么做，至少我是其中之一。几十几百年后，GitHub  将成为世界上最大的数字公墓，注册用户大部分都已去世，然而个人主页，项目，commit 历史 还述说着他们生前做过的事——就比如 Joe 的博客。这虽然是个比较 creepy 的推论，但从另一个角度想，却证明了人类的巨大进步：对抗死亡是人类文明的永恒主题，而我们已经实现了阶段性胜利。
#+end_quote

* Gitmemo
简单记录一下过程。

~git clone git@github.com:yihong0618/gitblog.git~ ,修改 ~config.toml~ 里的 GitHub Pages 的 url，因为这个项目通过 GitHub Pages 部署 Zola 的页面。

生成一个新的 GitHub secret，开启 issue 的读写权限，一定不要忘了在仓库的 settings 里打开 Actions 读写的权限。因为我就忘了。

在 Python 脚本里就可以自定义生成 README 的格式了。Zola 本身也提供了很多主题，在 ~config.toml~ 里配置就 ok。由于这个项目使用的还是 master 分支，GitHub 现在的默认分支是 main，因此涉及到的部分需要修改成 main。

GitHub issue 提供 tag 的功能，自带 markdown 编辑器和预览，也可以上传图片、文件、视频。对于记录来说功能足够了，检索也很方便。

这是新的 memo 地址：https://x.vandee.art/memo

我的 GitHub 仓库地址：https://github.com/VandeeFeng/gitmemo

* 记录与反抗
[[https://wiki.vandee.art/#%E6%B2%A1%E6%9C%89%E8%AE%B0%E5%BD%95%E5%B0%B1%E6%B2%A1%E6%9C%89%E5%8F%91%E7%94%9F%EF%BC%8C%E8%80%8C%E8%AE%B0%E5%BD%95%E6%9C%AC%E8%BA%AB%E5%B7%B2%E7%BB%8F%E6%98%AF%E4%B8%80%E7%A7%8D%E5%8F%8D%E6%8A%97][没有记录就没有发生，而记录本身已经是一种反抗]] ，都说历史是属于胜利者的，但那些被历史掩埋的气味和色彩永远都会存在。

看似平稳的秩序背后是无数抗争的呐喊与血泪，有自由就一定伴随着反抗。这些沉重的底色就好像在暗房里冲印的底片，色彩的背后是那些灰白的褪色了的故事。

看似稳定有序的秩序从来就是无序的，如果说反抗是为了秩序，这从开始就是一个伪命题。反抗这个词带有着默认被压迫的属性，而压迫和不平等是必然的，反抗作为它们的对立面其实是同等级的存在，并不需要添油加醋的加上那么多英雄色彩。太多所谓的反抗其实只是实现的落差带来的利己表演，只是一些出于本能的情绪和反应，这些在我的标准里不能称作是反抗，更准确的说来，应该是生物本能的自我保护。大多数人和事连反抗的对象都没有对上号，又谈何反抗？反抗的是这些不公，还是那些完全不符合人情道义的事物，还是和自己标准不相符带来的愤慨和不理解。所以我们一直在说的反抗，到底是在反抗什么？

我更愿意用正面的感情来描述反抗这个通过和压迫对立来表现的词语：“希望”，我欣赏的历史上的反抗大多是“希望”。正是因为希望那些永远不可能达到的事物，希望着自由和平等，我们才会一直努力的追求，奋斗，抗争，坚持，传承。

我记录这些并不是为了反抗什么，虽然带着同样的目的，但手段可以就是手段，它不象征任何。扫地僧扫地其实并不是为了什么，它只是在扫地，它的手段和目的已经融为一体互相转化了，但又不通过任何目的来驱使这个手段。

现在我自然还没有达到这种境界，就只是凭着直觉记录着，不反抗什么，只是保持希望，保持热爱，像大地一样承载和接受。大地愤怒么？它从来都很平静，但平静得让人类不敢轻易践踏自然的法则，这是比“反抗”更坚实、更伟大的力量，因为它会滋生希望而不是畏惧、愤怒和伤害。
