#+title: 2025 - 益
#+date: <2025-12-10 12:24>
#+description: 简单来说，艺术是关于抽象和重构的一种表达，用 0 和 1 来描述这个世界，表达自我是件挺 cool 的事情。和周易八卦类似，编程也是用极简单的基础元素，将眼中的世界解构，进而重构和抽象表达自我。
#+filetags: Ramble

* 益
今年我给自己的周易卦象是益，风雷益 ䷩，上巽（风）下震（雷），卦辞：“益：利有攸往，利涉大川。”

从去年开始我决定每年的总结使用周易里的卦象来描述，去年我给自己的关键词是 “[[https://www.vandee.art/blog/2024-12-12-the-summary-of-2024.html][需]]” 。

我自己对益这个卦象的理解是，风动积雨成雷。今年积累的东西还是比较杂，风代表动态的流动的变化，雷则是风动这个因的一个果。积累的东西如果没有汇聚起来，那么还是不成气候。

这个理解和周易里普遍的解释完全不同。我斗胆这么认为，易经最开始本是周文王在被囚禁之时，自己偶然突发奇想创造出来的，它有很大的历史局限性。之所以地位这么高，是因为这些甲骨重现了当时的历史，而占卜又满足了人们的奇思妙想。但其实占卜这个功能在易经里不那么重要，它的历史价值才是，我们从周文王占卜的这些内容里能了解到那个时代的样貌。

要说周文王是不是真的像易经里记载的那么想的，我想连他自己也说不清楚。也就是某天起来，周文王心里有很多困惑和苦闷，自己又是一个人，无法排解，于是就想，我来用龟壳算一卦吧。起初这些龟壳最基本的用途还是记录，可以简单理解为是周文王的日记本，里面大部分的内容都是今天谁谁谁干了什么，周文王觉得怎么怎么样，许多内容都很日常。换在今天，可能就是，今天起床太阳好大，风也很大，不知道楼下买烧饼的会不会出摊早点呢？

所以我觉得，对个人而言，周易里更有价值的是它构建的这个爻辞卦象体系，是周文王在当时处境里的心境与思考，是他解构当时客观世界的这种方式。用自然元素作为符号的映射，阴阳作为基础的构建单位，如此排列组合八八六四挂就可反应世间百态，有着万千变化。正所谓一生二，二生三，三生万物。三也可以理解成二的三次方，也就是八了。所以说，二进制还是牛的。

那些爻辞解析，我粗略的看过许多版本之后，就完全丢在一旁了。有这 64 个卦象就足够了。

2025-12-16 added:

2025 年度词汇：Slop - 由人工智能以大量方式生产的大量低质量数字内容。

via: https://www.merriam-webster.com/wordplay/word-of-the-year

#+begin_quote
Merriam-Webster’s human editors have chosen /slop/ as the 2025 Word of the Year. We define [[https://www.merriam-webster.com/dictionary/slop][slop]] as “digital content of low quality that is produced usually in quantity by means of artificial intelligence.” All that stuff dumped on our screens, captured in just four letters: the English language came through again.
#+end_quote

* 黑客帝国
不知道从什么时候开始，每年都会在不确定的时间看至少一次《黑客帝国》，从结果来看，这个现象勉强可以被描述为习惯。

对于这个电影作品我有多喜欢就不用说了，在 [[https://www.vandee.art/blog/2023-02-23-blue-or-red.html][蓝色药丸还是红色药丸？]] ，[[https://www.vandee.art/blog/2023-08-22-a-castle-in-the-air.html][镜花水月]] ，[[https://www.vandee.art/blog/2024-07-30-the-imitation-game-of-art.html][艺术的模仿游戏]] 里我都提到了它。

今年不出意外的我又看了 2 遍。最近的一遍是在昨天，没有缘由，就是又突然想看一遍。

结合今年我给自己的关键词 “益”，黑客帝国里可以聊的还是有很多。

我们这个现实世界的生存法则就像电影里的 Matrix 一样，很多事情虽然很难，但是它的弱点和限制恰恰就是这个规则本身。

Agent 斯密斯的能力强于普通 matrix 里的一般人。它有 matrix 赋予它的高程序权限，例如躲子弹、随意附身到 matrix 里的一般人上，速度和力量都高于普通人，在这个规则里，无论如何普通人这个程序设定都是不可能战胜 agent 斯密斯这个程序的。

墨菲斯带 Neo 去见了先知，先知说很遗憾你还不是救世主（the one），先知还提到，Neo 会遇到一个抉择，牺牲自己还是墨菲斯。

#+begin_quote
Neo：

Neo 有两层意思，neo 是希腊语里的 "new"，他将带领我们开启新的篇章。另外 Neo 其实还是一个 anagram，即变位词，由颠倒字母顺序而构成的词。Neo 是 one 的变位词。Neo is the One。Neo 就是那个唯一，那个救世主。

Neo 本名 Thomas A・Anderson，从希腊语角度考虑的话，Thomas 有 "twin" 和 "leader" 的意思。

Morpheus:
人物原型出自尼尔・盖曼大神的《Sandman》同名人物。Morpheus 这个词表示 The God of dreams, 是希腊神话里掌管梦的神。
#+end_quote

当墨菲斯被抓了之后，Neo 决定还是要再进入 matrix 去救他，崔妮蒂极力阻止，Neo 当时是这么说的：墨菲斯有自己的信念，他相信我是救世主，但很遗憾我不是。但是我也有我自己相信的东西，我相信我能把他就出来。正是因为没人试过所以才会成功。

这个时候 Neo 还是没有真正的觉醒变成 the one，但是他意识到了，他不必是 the one，他只需要做他自己。正是因为没人试过所以才会成功，这句话就表示 Neo 意识到了，matrix 里的设计完全只是一种程序设定，当他做出设定之外的事情，程序就会出 bug。

在营救墨菲斯的过程中，虽然 Neo 的能力小幅度觉醒了，可以躲子弹了，但是在和 agent 斯密斯的第二次交战中，还是中枪挂掉了。随后，导演可能恶搞了王子吻公主这个梗，反过来，让 Neo 被崔妮蒂一个爱的吻直接复活了。

这次死而复生让 Neo 彻底觉醒成了救世主。这个时候 Neo 在 matrix 里看到的都是源代码，直接空手停子弹，钻入斯密斯的身体，把他秒了。

Neo 的觉醒和复活。我是这么理解的：

Neo 在救出墨菲斯的时候，能力突破了一次，这是因为他开始相信，开始理解 matrix 只是一个虚拟的程序世界，真实的人可以无视这个世界里的很多规则，这些规则是 matrix 映射到被插管了的普通人的意识当中的。但这个时候 Neo 还没有突破这个规则本身，他只是相信自己，成为了自己。在面对先知给它应验的预言的时候，Neo 做出了遵循与自己本心的选择。

在黑客帝国的第二部里，我们就能了解到，其实还有很多 Neo，他们都是为了平衡 matrix 而被设定的一个变量，目的就是为了平衡 matrix 和人类这整个系统。电影里的锡安城，其实被摧毁重建了很多次。Matrix 的设计师，创造了许多版本，仅靠 matrix 都不能创造永久稳定的系统，无论怎么设计，程序都会出 bug，因此它设计了一个平衡，并引入了爱这个人类情绪变量。

先知其实也是一个程序，它和 Neo 一样都是为了平衡 matrix 和人类这整个系统。在系统初始化的时候就会生成一个先知程序，和一个 Neo 变量，先知告诉锡安城后续的故事走向（这象征着神话和传说），剧本也写好了，墨菲斯找到 Neo，拯救锡安城。

这些分析，在黑客帝国第三部的结尾反映的很明显。如果说 Matrix 的设计师是 matrix 之父，那么先知就是 matrix 之母，可能象征阴阳平衡吧。第三步结尾里，设计师和先知一起坐在椅子上，看着重新启动的 matrix 说到，这次又能持续多久呢？意思就是后面又会是第一部到第三部的循环。这太讽刺了不是么，当一个凡人突破了种种限制，牺牲了自己换来了和平，最后却还是在更大的设计之中。我想导演可能想表达的是，宇宙这个终极的物理法则，人类要尊重自然，尊重法则，找到人类的平衡之道。

回到前面说的第一部里 Neo 变成救世主这段剧情。Neo 选择救出墨菲斯牺牲自己这个选择就是 matrix 无法准确计算的那个情形。因为在 matrix 的构建中，它不设计不出人类的自我，它模拟不了人性，它无法用参数计算出这次的 Neo 去救出墨菲斯的概率有多大，也不是每一次的崔妮蒂都能让 Neo 爱上自己。

Neo 的复活是一个剧情设计。从电影剧本的逻辑上，不能解释为什么他能够复活并拥有了救世主的能力。这里更多的我觉得就是一种象征，象征着浴火重生，也表现了人类爱这种情感的力量。

非要解释的话，我觉得就是 Neo 的意识在 matrix 里中枪之后还没有完全消失，这个时候崔妮蒂象征的爱这种力量通过吻在现实世界强化了 Neo 的潜意识，让他意识到自己还没有死（电影设定里，人在 matrix 里会死是因为大脑因为 matrix 的映射以为这些是真的），再加上 Neo 自己之前强烈的信念，所以他这次彻底觉醒了(从第二部才能知道 Neo 本身就是这么设计的，它就是系统另外一个变量)，爱这个变量让 Neo 这个变量拥有了 matrix 里极高的程序权限。

回到今年我给自己的卦象“益”：

- 规则都是人定的，没有遇到的情况，规则的制定者它也没有先例，它也不知道应该怎么办。无论如何设计规则，都会有漏洞和 bug。

- 不存在绝对的平衡与完美，能够平衡恰恰也就是因为它的不完美。黑客帝国里许多设计元素都反映了阴阳的平衡。

- Neo 觉醒成为 the one 是两个觉醒。

  当 Neo 进入了这个规则，意识到这一切都只是幻象，他是 Human，它可以无视这些规则，这是摆脱了 matrix 之后人类意识的觉醒。

  第二个觉醒是，它是一个 matrix 里的高级程序，它相信自己有能力能救出墨菲斯之后，在 matrix 里做出的一般程序做不了事情就是 Neo 这个高级程序的能力。在相信之后才会开启这些能力。

  先知的预言就是 Neo 这个程序在 matrix 里被设计的目的和剧本。这个觉醒的条件恰恰就是 Neo 认清自己的时候（导演在先知和 Neo 见面的时候还特别强调了让 Neo 看头上的牌匾，写的就是认清自己），真正成为自己而不是程序给他设定的剧本。不得不说 matrix 设计师的这个设计很巧妙。

- 先知只是告诉你会发生的事，就算是既定的事情，就算是命中注定，自己对它不一样的理解，就会有不一样的因果。墨菲斯在电影里重复了很多次：先知只是告诉你会发生的事，它只是告诉你你应该知道的事情，仅此而已，我也不需要知道。

  Just believe ，and believe in yourself！

  宿命论是黑客帝国贯穿全篇想讨论的，这些设定也表达了导演对于宿命论的一些看法。

- Neo 成为的是它自己，所以才成为了 the one，他只是做出了自己作为人类本心的选择：救出墨菲斯。这和功夫熊猫里想表达的是类似的。神龙秘籍就是空白，映射的是自己的本心。

* 2025 回顾
今年在 [[https://www.vandee.art/blog/2025-12-09-native-linux-on-apple-silicon-mac.html][MacBook 上安装了 Linux]] ，Linux 成了我日常主要使用的操作系统。

[[https://wiki.vandee.art/#%E3%80%8AJust%20For%20Fun%E3%80%8B][Just For Fun]] 是今年我收获最大的一本书，就是 Linus 的自传。

今年构建了 [[https://www.vandee.art/blog/2025-06-10-nonotes-auto-completion.html][NoNotes]] ，它是我把 AI 和知识库结合起来使用的一点思考，在慢慢构建成 AI agent 的 memory layer。不管 LLM 怎么发展，它都可以作为一个数据接口，持续发挥作用。Context engineering 是今年大模型领域的一个热门，给 LLM 一个可以随着自己数据变化的 memory layer，AI 助手就能更了解自己的需求，从而生成和自己更相关的内容。

这是一个很大的市场，想象一下，现在的个人网盘变成个人 AI 记忆库，LLM 可以根据这些内容分析出你的个人画像，这才是更懂你的 AI 。我觉得大厂很快就会实现这些，这样能让用户把数据放在自己这里，这些数据才是最值钱的。与其现在明争暗斗到处搞别家的数据，各种算法跟踪用户习惯，不如透明直白一点，直接向用户要，提供这些数据储存的服务。Context 研究突破之后把 token 的成本降下来，Google 把 Google Drive 集成到自家模型服务我觉得就不是什么难事。

边学习 C 和 Rust，边搞了一些小玩意（在 Claude 的协助下）：
- [[https://github.com/VandeeFeng/GitNano][VandeeFeng/GitNano: GitNano is a mini, experiment implementation of Git.]]
- [[https://github.com/VandeeFeng/bili-tui][VandeeFeng/bili-tui: A tiny bilibili TUI client without AD and algorithm]]
- [[https://github.com/VandeeFeng/promptheus][VandeeFeng/promptheus]]
- [[https://github.com/VandeeFeng/smart-cmd][VandeeFeng/smart-cmd: command with AI suggestion in bash]]
- [[https://github.com/VandeeFeng/org-hover][VandeeFeng/org-hover: provides hover preview functionality for org links.]]
- [[https://github.com/VandeeFeng/Emacs-Hoarder][VandeeFeng/Emacs-Hoarder: Sync Hoarder bookmarks to local Org-mode or Markdown files]]
- [[https://github.com/VandeeFeng/RSS-CLI][VandeeFeng/RSS-CLI]]

今年玩 Linux 和写代码玩的挺开心，二进制很美妙。

简单来说，艺术是关于抽象和重构的一种表达，用 0 和 1 来描述这个世界，表达自我是件挺 cool 的事情。和周易八卦类似，编程也是用极简单的基础元素，将眼中的世界解构，进而重构和抽象表达自我。

这是今年我在探究艺术道路上最大的发现。
