#+title: The Passing Future
#+date: <2025-04-14 10:41>
#+description: 香菜有多好吃，吃了就自然会知道，喜欢吃的爱的不得了，不喜欢的碰也不会碰。但是，当所有的菜里都放香菜的时候，就是另外一回事了。
#+filetags: Ramble

最近博客更新的频次少了不少，原因之一是部分不成文的思考记录在了 [[https://x404.xyz/memo][GitMemo]] 。

更深层次的原因我自认为是：上个阶段我需要深度思考的问题已经解决的七七八八了，现在处在过度到下个阶段的过渡期。

佐证就是这些记录本身：

#+attr_html: :alt :class img :width 50% :height 50%
https://pic.vandee.art/images/task.png

现在每周 AI 都会自动根据我记录的这些思考帮我提出几个需要接着深入思考的问题，这些良性的多巴胺就像一根根柴火，让我思考的大脑一直烧的旺旺的。

* AI 举着喇叭
一个事物价值的大小，受到系统识别的影响。许多很好的事物，由于我没有相关的识别，它们对我来说就不会那么重要。

现在的 AI 就像互联网刚开始萌芽的时候，它已经不算是悄无声息地在改变我们的生活了，甚至是举着喇叭了，但是仍然会有许多群体没有相关的识别。

我不是一个 AI 的布道者，也没有相关的利益，也从来不想写 AI 怎么怎么好之类的东西。只是记录记录它带来的变化，记录记录它本身，之前的博客里也已经记录了不少。

香菜有多好吃，吃了就自然会知道，喜欢吃的爱的不得了，不喜欢的碰也不会碰。但是，当所有的菜里都放香菜的时候，就是另外一回事了。

说人话就是：AI 是未来一定会写进课本的东西。

* The Passing Future
这两年我一直在做各种记录，PKM 是对知识的记录，摄影是对感受的记录，博客是对思考的记录。

对我这些决策影响比较大的是 [[https://wiki.vandee.art/#%E3%80%8A%E6%97%B6%E9%97%B4%E7%9A%84%E7%A7%A9%E5%BA%8F%E3%80%8B][卡洛• 罗韦利的《时间的秩序》]] ，过去、现在、未来对我来说是一个范畴的事。

这些记录，一部分是给过去的，一部分是给未来的。

凯文凯利在一个[[https://wiki.vandee.art/#%E7%9C%8B%E8%A7%812033%20%E7%AC%AC%E5%8D%81%E4%B8%80%E6%9C%9F%EF%BD%9C%E5%86%AF%E5%A4%A7%E5%88%9A%C3%97%E5%87%AF%E6%96%87%C2%B7%E5%87%AF%E5%88%A9][访谈]]里谈到：思考未来最难的事情正是理解现在，而更关键的问题是什么是现在。

“现在”或者说“当下”，在我这里就是 The Passing Future。

我一直在想象，如果真的可以超越光速，到达时间的维度，应该怎么看待现在的物质世界。

因此我正在着手创造一个不会被现在的时间度量所限制的东西，它可以承载巨量信息，可以具象化思维，可以根据环境做出适应性的变化，它既不实际存在又无处不在，其他的现在还不能剧透。

在人工智能技术的帮助下，我觉得它一定是可以实现的。

随手拿起一张黑胶，指尖触碰唱片的封套，细细摩挲封面上岁月的痕迹。泛黄的边角，褪色的色彩，都是时间无声无息留下的讯息。唱针缓缓落下，与唱片纹路触碰，那些细微的、带着时光颗粒感的 “嘶嘶” 声，就像是一个时光隧道，一下子把我拉回到相隔的世纪。

无数这些相似时刻，都是永恒的缩影，是我们可以用心感受到的超越光速的时间旅行，都是我们的 The Passing Future。
