#+title: 薛定谔的 Linux
#+date: <2025-08-12 15:10>
#+description: Both stable and unstable until you linux.Linux 好玩是好玩，就是不太稳定，会遇到很多小问题。Linux 的图形界面和显示器协议的混乱和前端有的一拼。我的 Fcitx 输入法框架在 Emacs 和系统之间反复横跳，就像薛定谔的猫一样。有时候是 Emacs 里可以用，系统不能用，有时候又刚好反过来。
#+filetags: Linux Ramble

* TL;DR
Both stable and unstable until you linux.

Linux 好玩是好玩，就是不太稳定，会遇到很多小问题。Linux 的图形界面和显示器协议的混乱和前端有的一拼。

我的 Fcitx 输入法框架在 Emacs 和系统之间反复横跳，就像薛定谔的猫一样。有时候是 Emacs 里可以用，系统不能用，有时候又刚好反过来。

* 折腾记录
近道都是远路，尝试过几个大佬自己封装好的 Arch Linux，附带了桌面环境的安装和配置。是挺方便的，但是遇到一些小问题的时候，由于不知道他具体是怎么实现的一些功能，又要去看文档和源码。我这个电脑又比较老了，很多问题都没有现成的答案和别人的复现。

也尝试了 DHH 的 [[https://omarchy.org/][Omarchy]] ，桌面环境是 hyprland + Wayland，可能是我的电脑比较老了，运行起来有点卡顿。内置的 theme 我又不太喜欢，体验了 2 天之后，感觉不是很顺手。

最后决定使用 i3 和 X11，运行起来一点不卡，所有应用都是秒开。

#+attr_html: :alt :class img :width 70% :height 70%
https://pic.vandee.art/images/2025-08-12_16-18.png

** Arch Linux 初始安装
[[https://archlinux.org/download/][Arch Linux - Downloads]] 页面下载最新的 ISO 文件，有很多国内镜像可以选。写入 U 盘之后，进入 BIOS 启动 U 盘引导。

[[https://wiki.archlinux.org/title/Archinstall][archinstall]] 是 Arch Linux 的官方安装脚本，挺方便的，命令行输入 ~archinstall~ 启动安装脚本。

- 选择仓库镜像为 China
- 设置硬盘和分区：由于我的老电脑一个硬盘是小固态，一个是机械硬盘。在 ~manually partition~ 里手动设置把 arch 的系统（挂载 EFI Root）安装在固态，home 挂在在机械硬盘。设置完之后，设定 disk encryption 硬盘加密。
- 设定 root 密码并添加用户
- 设定 audio 为 pipewire，不在这里设定就播放不了音频，之后要单独安装。

Arch Linux 的镜像对国内环境太友好了，差不多 10 分钟就安装好了。

接下来就是大坑桌面环境。
** i3-X11
[[https://github.com/i3/i3][i3]] 的简洁实在太爱了。
*** 安装：
#+begin_src bash
sudo pacman -S i3 xorg xorg-xinit

echo "exec i3" > ~/.xinitrc
#+end_src

输入 startx 进入桌面环境。i3 会有一个引导界面，可以初始化生成配置文件到 ~/home/user/.config/i3/config~ 。
*** 配置
- 设置鼠标滚轮翻转

  编辑 /usr/share/X11/xorg.conf.d/40-libinput.conf 文件:

  #+begin_src bash
  Section "InputClass"
    Identifier "libinput pointer catchall"
    MatchIsPointer "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "NaturalScrolling" "True"
  EndSection
  #+end_src

- 我的自定义设置

  #+begin_src bash
exec --no-startup-id opensnitch-ui
exec --no-startup-id copyq
exec --no-startup-id feh --bg-fill /home/vandee/Pictures/create.jpg

bindsym $mod+period exec ghostty
bindsym $mod+b exec librewolf --new--windows
bindsym $mod+e exec emacsclient -c -a ""
bindsym $mod+f exec thunar
bindsym $mod+q kill

# bindsym $mod+Mod1+v exec --no-startup-id copyq show

# Gaps
gaps inner 5
smart_gaps on

# hide tiling window title bar
for_window [tiling] border pixel 1
smart_borders on

exec --no-startup-id fcitx5
  #+end_src

*** 其他设定
** Sway-Wayland
2025-09-01 added

在查找 X11 相关资料的时候了解到它有许多安全隐患，一些老旧的 issue 也很难再解决，我这个 Linux 菜鸟还是先用 Wayland 吧，Wayland 现在的势头和生态还是挺不错。

所以窗口管理器换成了 Sway。Sway 可以直接使用 i3 的配置文件，图形界面也和 i3 一样。用了 i3 一段时间之后就觉得 hyprland 有点臃肿。

dmenu 换成了 fuzzel，也很轻量。

安装： ~sudo pacman -S sway swaybg swaylock~ ,status bar 没有用 waybar，还是用的 i3 的配置文件。

保险起见，再装上 ~xdg-desktop-portal~ 。

- 设置鼠标滚轮翻转
  直接在 ~.config/sway/config~ 里加上：

  #+begin_src
   input * {
    natural_scroll enabled
    }
  #+end_src
* 冤家 Fcitx 和 Emacs

~~/.xprofile~

#+begin_src bash
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
#+end_src

~/etc/environment.d/90-fcitx5.conf~

#+begin_src bash
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
#+end_src

还有其他网上能查到的地方我都设置了。

现在他们两个的情况就是：有时候是 Emacs 里可以用，系统不能用，有时候又刚好反过来，还有的时候 Emacs 桌面不能用，但是 Emacsclient 可以，大多数时候在终端里 ~emacs -nw~ 可以，极少数情况都可以用。

这篇博客就是趁它们刚好都可以同时运行的时候抓紧时间写的！

用 Emacs rime 可以解决现在这个问题，但我更想弄明白到底是哪里出了问题。

我猜测可能的原因是因为 Emacsclient 在设置为系统的 service 之后，启动需要加载的环境和 i3 之间有顺序要求。有时候加载的顺序对了，环境就应用上了。

之前的猜测错了，是因为我用 systemd 启动了 Emacs daemon，而 i3 启动的 Fcitx5 获取的是 i3 session 的环境变量。之前就算我在 Emacs 里使用 ~getenv~ 指令获取到了 ~XMODIFIERS=@im=fcitx~ ，输入法框架还是出不来。由于某种原因，systemd 里启动的 Emacs 和 i3 的环境变量没有统一。找到一个最简单的方法，直接用 tmux 后台 ~Emacs --daemon~ 。

* 小结
这可能就是 Linux 一直不是流行的桌面环境的原因，它的桌面环境和 win、mac 比起来不那么稳定，不同的硬件配置和环境遇到的问题都不一样，得自己看文档解决。但这同时也是 hacker、nerd 和折腾仔（我）喜欢 Linux 的原因，它和 Emacs 一样，都是我的赛伯乐高。

Linux 就是我会一直使用下去的操作系统, [[https://www.vandee.art/blog/2025-07-16-linux-is-awesome.html][Linux 太自由了]] 。
