#+title: 稍后阅读新方案 Emacs-Hoarder
#+date: <2025-07-04 20:06>
#+description:
#+filetags: Emacs

* TL;DR
从 Omnivore 到 [[https://github.com/VandeeFeng/bookmark-summary ][Clip]] ,再到 ReadWise，一直没有找到一个符合自己需求和习惯的稍后阅读 + 高亮剪藏方案。再持续观察和试用 [[https://github.com/hoarder-app/hoarder/][Hoarder]] 之后，最终决定就是它了。

因此之前的 clip 就正式 [[https://memo.vandee.art/issue/63][停用]] 了。

* Hoarder
[[https://github.com/karakeep-app/karakeep][Karakeep]] （原 Hoarder），作者的解释是：

#+begin_quote
The name Karakeep is inspired by the Arabic word "كراكيب" (karakeeb), a colloquial term commonly used to refer to miscellaneous clutter, odds and ends, or items that may seem disorganized but often hold personal value or hidden usefulness. It evokes the image of a messy drawer or forgotten box, full of stuff you can't quite throw away—because somehow, it matters (or more likely, because you're a hoarder!).

Karakeep 这个名称的灵感来源于阿拉伯词语 “كراكيب” (karakeeb)，这是一个口语化术语，通常用来指代杂物、零碎物品，或者看起来杂乱无章但往往具有个人价值或隐藏用处的物品。它唤起了一个凌乱的抽屉或被遗忘的箱子的形象，里面塞满了你无法完全扔掉的东西——因为不知怎的，它很重要（或者更可能是，因为你是个囤积者！）。
#+end_quote

我还是习惯叫 Hoarder，后面也都用这个。

Hoarder 可以看作是一个精简版的 ReadWise，支持 RSS feed，书签导入，URL 导入，高亮笔记，webhook，还有简明的 API 文档。有移动端客户端，浏览器插件，支持 sefl-hosting。

结合 LLM 的功能是生成 tags 书签，生成 summary 总结，可以不使用。也支持 MCP。

除了这些之外，再没有其他臃肿的功能了。关注了这么久，这个项目的开发方向一直很稳定，没有加入杂七杂八的噱头功能。

部署也很方便（没有服务器就本地跑）：

#+begin_src bash
mkdir karakeep-app

wget https://raw.githubusercontent.com/karakeep-app/karakeep/main/docker/docker-compose.yml

# .env
KARAKEEP_VERSION=release
NEXTAUTH_SECRET=super_random_string
MEILI_MASTER_KEY=another_random_string
NEXTAUTH_URL=http://localhost:3000
#+end_src

它没有深度绑定 AI 反而是我现在决定长期使用它的原因了。

ReadWise 用了快一年了，实际的使用当中，ReadWise 的 AI 功能基本没怎么用，前几个月出来的可以根据 highlight 提问对话还是挺好用。

而且现在 PKM 里绝大部分的内容都已经接入了 [[https://www.vandee.art/blog/2025-06-10-nonotes-auto-completion.html][Nonotes]] 做向量相似检索和补全。

我现在需要的是一个多端同步，支持稍后阅读，RSS 订阅，高亮笔记的中转站，Hoarder 的功能正好很契合。尝试过自己搭，但是真的很麻烦，还是用现成的吧。

AI 速读没得灵魂，渐进式阅读，高亮剪藏更容易进入心流，引发深度思考。

它的缺点嘛，就是 UI 太丑了，而且移动端和浏览器插件的功能很简陋。

准备基于 Obsidian-Web-Clipper 自己做一个导入到 Hoarder 的插件。

* Emacs-Hoarder
写了一个小工具在 Emacs 里同步 Hoarder 的高亮。正好把 Gemini CLI 拉出来练练，Lisp 的括号真是 LLM 杀手。在重构代码的途中，每次都不能正确的处理括号，Claude、GPT 也是一样。

Github: https://github.com/VandeeFeng/Emacs-Hoarder

Hoarder 有 MCP 可以检索笔记、添加笔记，所以其他功能就不重复做了。后面想到什么方便的功能再慢慢加。

* Obsidian-Web-Clipper
用 Obsidian-Web-Clipper 已经很长时间了，这就是目前为止我用过最好的网页剪藏工具。

Github：https://github.com/obsidianmd/obsidian-clipper

几个亮点：
- 可以自定义剪藏的模板
- 可以结合 LLM 自定义 prompt 进一步优化剪藏的内容
- 内置了一个阅读器视图

Obsidian-Web-Clipper 提供了相当多的变量和语法，可以发挥想象设计出很多有意思的模板。具体可以查看 [[https://help.obsidian.md/web-clipper][帮助文档]] 。

就算不使用 obsidian，它也可以很好的融合到其他的工作流当中。

例如这个用在 Emacs 里的 org 格式剪藏模板：

#+begin_src

**{{title}}
<{{date|date:"YYYY-MM-DD ddd HH:mm"}}>

source: {{url}}

{{content}}

#+end_src

也可以直接生成 org 文件，甚至美观的 HTML 网页或者 SVG 小卡片方便社交网络分享。
