#+title: Intent Is All You Need
#+date: <2026-06-21 11:33>
#+description: 最开始接触 pi 的时候，就想着自己也造一个出来。最近的精力都放在了 phi 上，现在可以跑跑小任务了。从名字上也不难看出我对 pi 的喜欢。phi 也就是黄金比例 φ ,发音类似于英文单词 “fi”。phi 和 pi 一样，都让我联想到数学上的美感。
#+filetags: Ramble

看了眼上次 blog 的日期才发现有好久没有更新了。

前段时间 pi-memory-md 的更新基本停止了，感觉想做的内容差不多都做完了，现有的知识下，想不出什么新的好点子了（其实就是没钱用 token 了）。

最开始接触 pi 的时候，就想着自己也造一个出来。最近的精力都放在了 phi 上，现在可以跑跑小任务了。从名字上也不难看出我对 pi 的喜欢。phi 也就是黄金比例 φ ,发音类似于英文单词 “fi”。phi 和 pi 一样，都让我联想到数学上的美感。

Claude Code 官方说过，它最开始就是一个简易的小玩意，在使用中不断迭代成现在的样子,现在 Claude Code 的代码基本都是 AI 自迭代了。这就让我更想完成 phi 了。使用一个工具，和自己构建工具的感觉还是挺不一样的。学习和理解一个事物最直接的方式，就是上手。在构建 phi 的过程中，我又学到了许多关于 TUI，agent 的知识。

对于我来说，phi 不仅仅是一个满足我个性化需求的 CLI/TUI Coding Agent，它更是我以后想扩展的 intent 接口。

* Intent interface

如果说传统的用户交互界面分为 TUI 和 GUI，那么 AI 成为基础设施之后，我觉得 intent 就是最关键的。传统的用户界面就是用户意图和产品之间的桥梁，AI 可以把用户意图转换成更多的形式，可以传递更多的信息。

传统的交互里，我们通常需要在界面上点击，意图通过按钮和菜单传递，意图通过用户特定的交互动作来传递（暂不考虑 VR 眼镜的虚拟现实交互）。AI 把意图转换为 token 和一系列的 agent 工作流，从 action -> intent，变成了 intent -> intent。

AI 眼镜和 AI 可穿戴设备也就是在用户 intent 和 AI agent 之间的一种信息传递介质。当模型的多模态能力更强之后，用户的表情和动作就能传递更多的意图了。除了意图，对于 AI 交互来说，我觉得另一个也很重要的是场景。相似的意图在不同的场景下，想表达的含义可能完全不同。

今年 agent memory 和 token 压缩的项目看到很多，感觉这方面越来越成熟了，AI 输出内容的相关性越来越高，这也是我们感觉 AI 越来越懂自己的一个原因。再往后，我觉得应该是 intent 的转化。

实际的应用场景里，很多时候我们觉得 AI 不好用，也就是感觉它不能理解自己的需求，没有准确输出任务结果。这和模型能力有一定关系，但我觉得根本的原因是在设计上，AI 应用没有根据用户意图来设计。实现起来我觉得也不是不可能，主 agent 下，设计一个 intent agent 专门来分析用户意图已经不是很难的事情。现在普遍的 agent 设计是任务驱动，把用户的输入转换为 agent 的任务，在一系列 loop 下得到一个可校验的结果，主 agent 或校验 agent 验证之后返回用户最终的结果。

从任务驱动到意图，我觉得最简单的处理就是加上场景设计。现阶段，一轮 agent 任务工作流里的目标往往是模型根据用户输入总结抽象成的一个 agent message 传递给 subagent，执行 agent loop。加上预设场景之后，用户的意图就更准确了。例如外卖软件里，用户输入吮指原味鸡，如果是一般的 agent，这个任务可能会偏离的很远，但如果 agent 明确的知道了应用场景（例如 system prompt 里设定），它就能知道用户是在点外卖。

上下文工程的具体实现，和有没有场景设计是两回事。在 system prompt 里预设的 role 和场景设计也是两回事。我觉得意图+场景的设计应该融入到 agent harness 里。

所以传统的 UI 设计下，按钮这种用户动作驱动的意图交互肯定是无法满足 AI 驱动的交互的。在我的设想里，我打开一个 AI 驱动的软件，界面里应该是根据 memory，用户画像，特定场景，提供一些意图链。例如您是否还想吃吮指原味鸡？需要我帮您预订么，根据您习惯的进餐时间，11:00 可以么？最近吮指原味鸡您吃太多了，建议多吃点蔬菜呢！需要来一份蔬菜水果沙拉么？

这些都不是几个按钮和 AI 搜索框可以解决的。传统的搜索建议里其实都有这部分内容，但是它很让我反感，感觉是窥探了我的隐私，下面显示一大堆的搜索建议也不是很准确。但是如果是我的私人 AI 助手告诉我，那感觉就完全不一样了🤣，它怎么这么懂我！

当这些特定场景和服务的软件也成为 agent 工作流里的一个节点的时候，我觉得这些都是可以实现的，这些软件也都没有太大必要做单独的软件和 UI 了。只不过用户可能需要支付更多的会员费了🤣。

更极端一点，我觉得甚至可以推出用户自定义 UI 的服务，agent 成为 intent 的驱动之后，做什么样的 UI 感觉也不太重要了，反正现在各大场的 Chat UI 看起来也差不多，还不如让用户自定义呢，我进入软件只是要语音输入或者打字而已，UI 张什么样不太关键吧。OpenClaw 一个吸引用户的地方，就是它可以自部署，通过不同的平台接入。把 agent 接口给用户，让用户自定义 “皮肤” ，根据积分解锁稀有的 agent 虚拟形象（集五福春节特供财神爷）,不是可以再赚一笔？


* Phi

#+attr_html: :alt  :class img :width 50% :height 50%
https://pic.vandee.art/images/phi.png

Phi 的 TUI 和 pi 很像，说是抄也完全没问题。用习惯 pi 了，footer 的部分看着挺舒服的，不想换了，干脆就搬过来了。

在考虑很久之后，phi 选择了 Rust + Lua，一个可执行文件（现在是 16.2M） + lua 脚本就可以很方便的在其他环境里使用了。我实在不太喜欢 TypeScript，虽然 ts 对于 AI 应用很友好，模型在训练上对 ts 也很熟悉。用 Rust 而不是 C 是因为我现在的 C 水平太差了，判断不了 LLM 生成代码的问题，而且用 C 要从头写许多基础设施。Rust 现在也是刚入门，但是编译器对 AI 太友好了，Rust 的基础库也很全。

Bash 的部分和 Claude Code 一样，直接通过 shell，内置 bubblewrap sandbox。Agent 和 subagent 作为一个特殊的 tool 来调用，我觉得 Claude Code 的这个处理很好。

TUI 在 crossterm 的基础上设计。界面主要由内容输出区、输入区、菜单栏、运行状态和事件通知 chrome 组成，并支持 lua 自定义。没有 alternate screen，完全使用终端的 scrollback buffer。这个原生终端的设计取舍带来了许多麻烦，在处理 streaming 内容的滚动，展开折叠内容的时候，学到了许多终端的相关知识。

Agent framework 部分，在 rig 的基础上，单独做了 SDK 让 TUI 调用。Agent 抽象为三层：定义层、运行层、事件层，通过事件和状态设计了 agent events, agent loop，hook，方便自定义不同 agent 阶段的行为。SessioHost -> agent runtime -> agent event -> agent turn，message、tool call、thinking 这些 agent 的 event/result 在 TUI 里消费映射成独立的 block。

之前研究过一段时间 nvim，入门了一点 lua，所以脚本语言选择了 lua。lua 插件可以像 pi 一样自定义插件，自定义 tool，添加自定义 TUI 的 block。

Phi 也提供 RPC 、TUI 、CLI 三种交互模式。SKILL，slash command，MCP，parallel agent 也都支持。

Phi 借鉴了 Claude Code，pi 的许多底层设计（TUI 部分偷懒了，用 rust 重写了 pi 里 footer 的部分内容），原创的地方有，但是不多。50% 的代码是在 pi 里 AI 填空生成。手写再让 AI 填空是我现在可以接受的 AI 生成程度，完全让 AI 自己生成总感觉少了点什么。等可以完全手写了，就不用 AI 了。敲代码的时候的那种心流体验，是 AI 生成替代不了的。

不想继续使用 pi 的一个原因是，它的许多设计需要为 openclaw 服务，现在 AI 迭代的更新越来越频繁，自定义起来就越来越麻烦。自己做的更熟悉，更方便实现自定义功能，特别是我后面需要实现的 intent 接口。

pi + pi-memory-md 让 phi 的实现轻松了许多，再次感谢 pi 的开源！
