#+title: What are you waiting for?
#+date: <2026-07-26 14:03>
#+description: AI 提供了技能和知识的 buff，但它更提供了获取技能和知识的 buff。我从来没有觉得，学习能像现在有了 AI 之后效率这么高。这些远路才是捷径。这就好像搭积木，AI 帮我们搭建的越多，对它的依赖就越多，跳过了这些必经之路，后面的积木会越来越难。
#+filetags: Ramble

[[https://codex-resets.com/][Codex Resets]] 应该是最近的热门网站了，OpenAI 为了推广最新的 GPT-5.6 模型频繁的重置。[[https://status.openai.com/][OpenAI Status]] 是另一个，同时最近 OpenAI 也出现了几次服务中断。

我们等待着额度的刷新和功能恢复。但是，What are you waiting for?

* Intro

这几天的这种情况，应该能够叫作戒断反应了。我一直对 AI “软隔离”，所以这个戒断反应很小。

感觉上，有点像以前停电、停网的时候，突然一下子好像不知道可以干嘛了。但是马上我又意识到，它们只是很像而已，AI 现在还不是基础设施，没有它我的一切也还是可以很正常的继续。

但是 AI 迟早有一天会成为基础设施，我们的生活和工作会像依赖电力和网络一样，依赖 AI 和算力。我也很期待 AI 给生活可能带来的便利。所以我想再继续思考，在这个过渡期，还应该做些什么。

随即回到 Emacs，开始了这篇 blog。

* What are you waiting for?

巴菲特多次在不同的讲话里提到类似的观点：

#+BEGIN_QUOTE
“Take the job that you would take if you didn’t need the job—that’s what I’ve got.”

“You want to be doing something you would do if you didn’t need the money. And most people do need the money. But if you’re in the position where you don’t, you should be doing what you would if you didn’t need the money.”

via: https://fortune.com/2024/08/30/warren-buffett-career-advice/ , https://www.berkshirehathaway.com/letters/2021ltr.pdf
#+END_QUOTE

把上面观点里的 money 换成 AI 同样成立。

AI 是一个放大器，可以帮助我们在技能缺失的情况下，提供一个强力 buff，让我们一次性的达成某个目标。我强调了技能缺失，暂时，一次性，因为我一直觉得，真正应该提升的还是这个缺失的技能。

AI 出现之后，许多网络内容里都会提到类似的：有了 AI 之后我实现了许多以前无法实现的想法。那么为什么之前一直没有实现呢？抛开现实的原因，剩下的那个可能就是懒了。从接触 AI 到现在，我一直在问自己这个问题。

所以每次 AI 帮助我实现一个小玩意之后，我都会强迫自己继续学习这个实现的过程和知识。这并不是因为我有多喜欢学习（当然我确实很喜欢学习🤣），而是总感觉这样并没有真正收获什么。

AI 帮助我配置好了 Linux -> 学习 Linux 的相关知识，AI 帮助我写好了一段代码实现 -> 学习这段代码，AI 帮我生成了一段和弦旋律 -> 学习相关的乐理。我觉得，这应该是现在 AI 刚开始发展的过渡期对待 AI 更一劳永逸的态度。

更明确一点，我觉得 token 更应该投资在知识和能够帮助自己实现目标的工具上，而不只是提供结果。例如，把 AI 帮我看论文 -> AI 构建帮我看论文的工具。

AI 提供了技能和知识的 buff，但它更提供了学习技能和知识的 buff。我从来没有觉得，学习能像现在有了 AI 之后效率这么高。

有了 AI 之后，我逐渐掌握了许多计算机基础知识、Linux 成为了日常使用的系统、构建了许多以前无法独立实现小玩意、学习了许多代码知识，等等。让我们真正感觉到充实和满足的，一直就应该是这些自我提升。

这些远路才是捷径。这就好像搭积木，AI 帮我们搭建的越多，对它的依赖就越多，跳过了某些必经之路，后面的积木会越来越难。

没有这些强力模型，有本地小模型代码补全，我正在进行的一些项目也就是慢一点而已。

* Others

这几年，我慢慢形成了一个很有意思的循环：想法 -> AI 讨论提出问题 -> AI MVP 可能性实现 -> 学习和复现 -> 新的想法。

最开始我批判过现在互联网内容已经没有不是和 AI 相关的了，但是这一年多自己的 blog 内容也都是和 AI 相关的。这也并不矛盾，AI 有好的部分也有不好的部分，只承认一部分才是矛盾的。这又让我想起了乔帮主的那句名言：在一个产品 ( iPhone ) 出现之前，用户根本就不知道他们想要什么！

AI 出现之后，纠结对错的口水战没太大意义，谁也不能让历史重来一次。到现在我仍然很讨厌 AI 带来的一些现象，但是也非常感谢 AI，让我更明确了 What are you waiting for.
